js/components/data-sources.js
Fixed Data Sources (Achilles Web) reports to refresh when data source toggle (fixes #114)
=> Fixed Data Sources reports to refresh when data source toggle (fixes #114)

js/components/data-sources.html, js/styles/achilles.css
=> achilles.css was messing up bootstrap styles. confined it to

js/jnj.chart.js
Sorry, it looks like the search-and-replace strategy for my recent fix (#141) missed three instances.
=> Fix 3 instances of the Y_PREVALENCE_1000PP check

index.html, js/app.js, js/main.js
Fixes #252
Fixes #211
The title computed handled specific currentView() values. If any are missing, please report it here, and updates can be made.
=> Added binding to title of page.

js/components/conceptset-manager.js
Bug fix for selecting all mapped concepts.
=> Fixes #257

js/modules/cohortbuilder/CohortExpression.js
Initalize QualifiedLimit event from proper element from cohort definition.
=> Fixes #277.

index.html, js/app.js, js/components/atlas-state.js, js/components/atlas.cohort-editor.js, js/components/cohort-definition-manager.html, js/components/cohort-definition-manager.js, js/components/cohort-definitions.html, js/components/concept-manager.html, js/components/concept-manager.js, js/components/conceptset-manager.html, js/components/conceptset-manager.js, js/components/configuration.html, js/components/configuration.js, js/components/data-sources.html, js/components/data-sources.js, js/components/importer.js, js/components/loading.html, js/components/loading.js, js/components/negative-controls.js, js/components/search.html, js/components/search.js, js/main.js, js/modules/WebAPIProvider/VocabularyProvider.js, js/styles/atlas.css
This PR will provide dynamic component loading to replace the current approach of toggling visibility of components.
=> Dynamic component loading

js/components/atlas.cohort-editor.html, js/components/home.html, js/components/home.js, js/components/ir-manager.html, js/components/ir-manager.js, js/modules/cohortbuilder/components/CohortExpressionEditor.js, js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html, js/modules/cohortbuilder/components/ConditionEra.js, js/modules/cohortbuilder/components/ConditionOccurrence.js, js/modules/cohortbuilder/components/Death.js, js/modules/cohortbuilder/components/DeviceExposure.js, js/modules/cohortbuilder/components/DoseEra.js, js/modules/cohortbuilder/components/DrugEra.js, js/modules/cohortbuilder/components/DrugExposure.js, js/modules/cohortbuilder/components/InclusionRuleEditorTemplate.html, js/modules/cohortbuilder/components/Measurement.js, js/modules/cohortbuilder/components/Observation.js, js/modules/cohortbuilder/components/ObservationPeriod.js, js/modules/cohortbuilder/components/ProcedureOccurrence.js, js/modules/cohortbuilder/components/Specimen.js, js/modules/cohortbuilder/components/VisitOccurrence.js, js/modules/cohortdefinitionviewer/components/CohortExpressionViewerTemplate.html, js/modules/databindings/contentEditable.js, js/modules/databindings/main.js, js/styles/atlas.css
This is the PR branch that is to close out any remaining updates for the 1.4 release.
Currently this has the following changes:
- Updates the milestone reference to pull down the github closed issues.
- Added a export link for IR analysis to the IR Analysis UI
Further changes required to for the 1.4.0 release should be applied to this branch.
=> V1.4.0 pre

js/app.js, js/components/configuration.html, js/components/configuration.js, js/components/data-sources.js, js/main.js, js/modules/WebAPIProvider/CDMResultsAPI.js, js/modules/WebAPIProvider/EvidenceAPI.js, js/modules/WebAPIProvider/VocabularyProvider.js
Adjusted client-side calls to WebAPI to use the route format {service}/{operation/key}...
Also, fixes #336.
=> Route cleanup.

js/components/concept-manager.js, js/components/ir-manager.js
Removed logging from IR Manager.
Fixes #367.
=> Cleanup subscriptions when component is disposed.

js/components/ir-manager.html, js/components/ir-manager.js, js/modules/iranalysis/components/editor.js
=> Handle component reloads when route changes.

js/components/cohort-comparison-manager.html, js/components/cohort-definition-manager.html, js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html, js/modules/cohortbuilder/components/CriteriaGroupTemplate.html, js/modules/cohortbuilder/components/CustomEraStrategyTemplate.html, js/modules/cohortbuilder/components/DateOffsetStrategyTemplate.html, js/modules/cohortbuilder/components/WindowInputTemplate.html, js/modules/databindings/autocompleteBinding.js, js/modules/databindings/htmlValueBinding.js
=> Autocomplete fix

js/components/cohort-definition-manager.html, js/components/cohort-definition-manager.js
https://github.com/OHDSI/Atlas/issues/418
=> Add Impala tab showing cohort generation SQL.

js/components/data-sources.js, js/jnj.chart.js
Changed per @jungsungjae suggestion and normalized the histogram interval to 100 from 120 while allowing the x-axis to grow in the event that there are persons aged > 100.
=> Fixes #377

js/components/report-manager.html
@anthonysena Hi Anthony, I just noticed there's a bug in the report-manager.html for the entropy div. There's a div tag missing ending slash. I have fixed that. Please review. Thanks!
=> DIXON-3 => fix div missing ending tag.

js/components/data-sources.js, js/components/report-manager.js, js/modules/circe/components/CohortConceptSetBrowser.js, js/modules/cohortbuilder/components/FeasibilityIntersectReport.js, js/modules/iranalysis/components/report.js
=> Databindings eventListener API change upate

js/components/data-sources.js, js/components/visualizations/concept-by-index.js
There was a few places where colors were not being properly set, and this PR fixes those issues.
=> Set proper color option for atlascharts.

js/components/report-manager.js
@anthonysena  Hi Anthony, please review this. Thank you!
=> fix js errors for removing jnj-chart

js/modules/cohortbuilder/AdditionalCriteria.js, js/modules/cohortbuilder/CohortExpression.js, js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html, js/modules/cohortbuilder/components/CriteriaGroup.js, js/modules/cohortbuilder/components/CriteriaGroupTemplate.html, js/modules/cohortbuilder/options.js, js/modules/cohortdefinitionviewer/components/CohortExpressionViewerTemplate.html, js/modules/cohortdefinitionviewer/components/CriteriaGroupTemplate.html, js/styles/atlas.css
Added Gap input field to specify the collapse window.
Added 'restrict to same visit' option in correlated criteria.
=> CIRCE UI Enhancements

.gitignore, js/modules/cohortbuilder/CriteriaTypes.js
Fixes #467
Added /node_modules/ to .gitignore
=> Fixes #467

js/modules/iranalysis/components/editor.html, js/modules/iranalysis/components/editor.js
Fixed malformed div tag.
Fixed JSHint errors.
=> Fixes #469

js/components/data-sources.html, js/components/data-sources.js, js/components/welcome.js
Implements a feature requested in https://github.com/OHDSI/WebAPI/issues/227
- adds new Frequency Distribution graph in DataSources
=> Datasources Expansion and Improved Speed

js/components/plp-r-code.html
=> Updated PLP Code

js/components/data-sources.html, js/components/data-sources.js, js/components/welcome.js
Depends on changes that are under review in OHDSI/Achilles#219 and OHDSI/WebAPI#252
=> Frequency distribution

js/app.js, js/components/cohort-definition-manager.html, js/components/cohort-definition-manager.js, js/components/faceted-datatable.js, js/main.js, js/modules/WebAPIProvider/CohortFeaturesAPI.js, js/modules/cohortbuilder/components/FeasibilityReportViewerTemplate.html, js/modules/cohortfeatures/FeatureSection.js, js/modules/cohortfeatures/components/CohortFeatureBrowser.js, js/modules/cohortfeatures/components/CohortFeatureBrowserTemplate.html, js/modules/cohortfeatures/main.js, js/modules/cohortfeatures/tableConfig/DemoTableColumns.js, js/modules/cohortfeatures/tableConfig/DistributionTableColumns.js, js/modules/cohortfeatures/tableConfig/DistributionTableOptions.js, js/modules/cohortfeatures/tableConfig/DomainTableColumns.js, js/modules/cohortfeatures/tableConfig/DomainTableFilteredColumns.js, js/modules/cohortfeatures/tableConfig/DomainTableFilteredOptions.js, js/modules/cohortfeatures/tableConfig/DomainTableOptions.js, js/modules/cohortfeatures/tableConfig/FormattingOptions.js, js/styles/atlas.css
This PR introduces the UI elements to brows cohort features (introduced in OHDSI/WebAPI#257).  
Changes include:
- Cohort feature browser utilizing facet tables to filter features and grouping by domain.
- New generate button style
- Faceted datatable fix to update when removing data.
=> Cohort characterization

js/components/cohort-comparison-multi-r-code.html
Updates to the R-code generated by the estimation module to reflect the updated methods libraries. Specifically:
- CohortMethod (2.4.4)
- Cyclops (1.3.0)
- DatabaseConnector (2.0.0)
- EmpiricalCalibration (1.3.5)
- FeatureExtraction (1.2.3)
- SqlRender (1.4.3)
=> Changes to estimation R code module to reflect CohortMethod v2.4.4.

js/components/cohort-comparison-multi-r-code.html
Small update to the R-code generated in the estimation specification editor to specify a specific release of FeatureExtraction and CohortMethod.
=> Estimation r-code reference specific package versions

js/components/cohort-definition-manager.html, js/styles/atlas.css
This PR addresses a UI issue with the generate cohort features dropdown.
=> 2.2.0 Fixup

js/components/plp-r-code.html
Thanks to @jswerdel for catching this one!
=> PLP r-code bug fix

js/components/cohort-comparison-multi-r-code.html
=> Fixes #500

js/components/conceptset-manager.js
This fix must be tested with the code pushed in OHDSI/WebAPI#264.
=> Fixes #502

js/components/report-manager.html, js/components/report-manager.js
Hi Anthony @anthonysena , I have re-done this off of feature-integration branch. Please review when you get a moment. Thank you!
=> data completeness visualization

js/modules/WebAPIProvider/AuthAPI.js
=> Updated auth checks to post/put for create/update.

js/modules/WebAPIProvider/AuthAPI.js
For https://github.com/OHDSI/Atlas/issues/578
=> Fixed auth token disclosure

js/components/ir-manager.html, js/components/ir-manager.js, js/modules/WebAPIProvider/AuthAPI.js
https://github.com/OHDSI/Atlas/issues/580
=> Fixed buttons state for IR

js/modules/databindings/datatableBinding.js
https://github.com/OHDSI/Atlas/issues/592
=> fixed 'Unexpected token ...' in Safari

js/components/cohort-definition-manager.js
fixes https://github.com/OHDSI/Atlas/issues/570
=> Update reports on Job completion

js/components/cohort-comparison-manager.js, js/components/cohort-comparison-multi-r-code.html, js/components/cohort-comparison-print-friendly.html, js/components/cohort-comparison-r-code.html, js/components/plp-print-friendly.html, js/components/plp-r-code.html, js/components/plp-spec-editor.js, js/modules/cohortcomparison/ComparativeCohortAnalysis.js, js/modules/plp/PatientLevelPredictionAnalysis.js
Bug fixes for PLE/PLP editors.
=> Hotfix 2.3.1

js/components/welcome.html, js/components/welcome.js
=> No Lockout Policy

js/components/data-sources.js
=> Measurement Reports are missing plots

js/components/cohort-comparison-multi-r-code.html, js/components/cohort-comparison-r-code.html
=> Vocabulary schema not supported

js/modules/cohortbuilder/components/CohortExpressionEditor.js, js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html
=> Add scroll-pane to inclusion rule navigation.

js/app.js, js/components/atlas-state.js, js/components/cohort-comparison-manager.js, js/components/cohort-comparison-multi-r-code.html, js/components/cohort-comparison-r-code.html, js/components/cohort-definition-manager.html, js/components/cohort-definition-manager.js, js/components/concept-manager.js, js/components/conceptset-manager.js, js/components/configuration.html, js/components/configuration.js, js/components/data-sources.js, js/components/explore-cohort.js, js/components/negative-controls.js, js/components/profile-manager.html, js/components/profile-manager.js, js/components/report-manager.html, js/components/roles.js, js/components/source-manager.html, js/components/source-manager.js, js/main.js, js/modules/WebAPIProvider/AuthAPI.js, js/modules/WebAPIProvider/RoleAPI.js, js/modules/WebAPIProvider/SourceAPI.js, js/styles/atlas.css
=> User Interface for Daimon / Source Configuration

js/modules/databindings/datatableBinding.js
Closes https://github.com/OHDSI/Atlas/issues/641
=>  Fixes security issue with possibility to inject external link

js/components/atlas.cohort-editor.html, js/components/atlas.cohort-editor.js, js/components/cohort-definitions/cohort-definition-manager.html, js/components/cohort-definitions/cohort-definition-manager.js, js/modules/circe/components/CohortConceptSetBrowser.js, js/modules/circe/components/CohortConceptSetBrowserTemplate.html, js/modules/circe/components/style.css, js/modules/cohortbuilder/components/ConceptSetSelectorTemplate.html
=> Updating Concept Sets in a Cohort by Swapping for Another

js/components/conceptset/style.css
=> button group markup

js/app.js, js/components/cohort-definitions/cohort-definition-manager.html, js/components/cohort-definitions/cohort-definition-manager.js, js/components/conceptset/conceptset-list-modal.html, js/components/conceptset/conceptset-list-modal.js, js/components/conceptset/conceptset-manager.html, js/components/conceptset/conceptset-manager.js, js/components/faceted-datatable.html, js/components/faceted-datatable.js, js/config.js, js/main.js, js/modules/WebAPIProvider/ConceptSetAPI.js, js/modules/databindings/datatableBinding.js, js/modules/databindings/main.js, js/modules/databindings/tooltipBinding.js, js/services/ConceptSetService.js
https://github.com/OHDSI/Atlas/issues/31
=> Atlas 31 ancestors in concept tab

js/components/conceptset/conceptset-manager.html, js/components/negative-controls.html, js/components/negative-controls.js, js/modules/WebAPIProvider/ConceptSetAPI.js, js/modules/WebAPIProvider/EvidenceAPI.js
Changes related to OHDSI/WebAPI#345
=> Use Common Evidence Model for negative controls

js/components/home.html, js/components/home.js, js/components/negative-controls.html, js/components/negative-controls.js, js/components/report-manager.html, js/components/report-manager.js, js/modules/cohortdefinition/components/view/reporting/cost-utilization/visit-util.html
A collection of pre-release fixes that we needed to perform prior to the 2.4 release
=> Release 2.4.0 fixes

js/components/negative-controls.html
Fixing the URLs for Negative Control references
=> Closes #668

js/components/source-manager.html, js/components/source-manager.js
closes https://github.com/OHDSI/WebAPI/issues/381
=> Extract username and password from connection string into separate fieldsc

js/styles/atlas.css
=> UI is broken if username is too long

js/components/cohort-comparison-manager.js, js/components/plp-manager.js, js/modules/WebAPIProvider/AuthAPI.js
Fixes https://github.com/OHDSI/Atlas/issues/686
Fixes display of PLE / PLP executions history when some DS was deleted
Fixes AuthAPI after clean up of localStorage
=> PLE / PLP executions history display fix

js/components/cohort-comparison-browser.js
=> no message

js/main.js, js/modules/WebAPIProvider/ExecutionAPI.js
=> fixed execution engine ping

js/components/report-manager.html
Fixes https://github.com/OHDSI/Atlas/issues/707
=> Fixed usage of endpoints for Drug Util reports

js/components/cohort-comparison-manager.html, js/components/cohort-comparison-manager.js
=> disabled buttons (PLE, view results) based on results

js/components/conceptset/conceptset-browser.html, js/components/conceptset/conceptset-browser.js, js/services/file.js
=> added fileService to save files from ajax

js/components/cohort-definitions/cohort-definition-manager.html, js/components/cohort-definitions/cohort-definition-manager.js, js/modules/WebAPIProvider/CohortDefinitionAPI.js
=> Invalidate cohort generation

js/components/cohort-definitions/cohort-definition-manager.html, js/components/cohort-definitions/cohort-definition-manager.js, js/components/modal-pick-options.html, js/components/modal-pick-options.js, js/components/modal-pick-options.less
Fixes https://github.com/OHDSI/Atlas/issues/719. The change approved with @pbr6cornell
=> Added popup to select which Utilization analyses to run

index.html, js/app.js, js/components/configuration.html, js/components/configuration.js
=> Cannot create new DS from UI in freshly deployed Atlas

js/components/plp-r-code.html
Closes https://github.com/OHDSI/Atlas/issues/740
=> PLP code generation fix

js/components/conceptset/conceptset-browser.js, js/services/file.js
Closes https://github.com/OHDSI/Atlas/issues/744
=> Fixed navigation to Concept Sets page

js/components/cohort-definitions/cohort-definition-manager.html, js/components/cohort-definitions/cohort-definition-manager.js, js/components/home.html, js/components/plp-r-code.html, js/components/user-bar.js, js/components/welcome.html, js/components/welcome.js, js/main.js, js/modules/WebAPIProvider/AuthAPI.js, js/modules/databindings/tooltipBinding.js
Some other fixes from upcoming 2.4.3 got here too
=> Added authentication manager for Google IAP

js/components/cohort-definitions/cohort-definition-manager.js, js/components/user-bar.js, js/components/welcome.html, js/components/welcome.js, js/main.js, js/modules/WebAPIProvider/AuthAPI.js
Closes https://github.com/OHDSI/WebAPI/issues/479
Pls, leave Merge button for me - testing is still in progress
=> Improvements for auth handling to support different auth managers (regular and proxy-based)

js/components/cohort-definitions/cohort-definition-manager.js
=> Progress bar of Heracles shows 120%

js/components/ac-access-denied.js
requirejs won't resolve the file in wrong case
=> fixed case in file name

js/modules/cohortdefinition/components/view/reporting/cost-utilization/base-drug-util-report.js
Fixes https://github.com/OHDSI/Atlas/issues/697
=> Fixed name of query param in Drug Util report

js/components/job-manager.html, js/components/job-manager.js
Issue https://github.com/OHDSI/Atlas/issues/750
=> Add a name of a person who kicked off a job (#750)

js/components/data-sources.js
Fixes https://github.com/OHDSI/Atlas/issues/764
=> Fixed calculation of data for histograms in Data sources

js/modules/databindings/tooltipBinding.js
fixes https://github.com/OHDSI/Atlas/issues/772
=> Fixed html rendering in tooltip

js/pages/data-sources/data-sources.js
=> Fixed re-rendering of the data sources select control

js/components/role-details.html, js/components/role-details.js, js/components/role-details.less, js/modules/databindings/datatableBinding.js
fixes https://github.com/OHDSI/WebAPI/issues/507
=> Added select/deselect all users in role screen

js/components/user-bar.html, js/components/user-bar.js
=> Removed display of notifications button for unauthorized users

js/modules/cohortdefinition/components/view/reporting/cost-utilization/persons-exposure.html
fixes https://github.com/OHDSI/Atlas/issues/722
=> ATLP-372. Changed report label to 'Exposure/p 1k/year'

js/app.js, js/pages/configuration/routes.js, js/services/http.js
=> Fixed navigation to DS page at Configuration screen

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/services/CohortDefinition.js, js/styles/atlas.css
Added 'By Person' and 'By Event' tabs under cohort generation reports.
=> Added 'By Person' inclusion report view.

js/components/modal-pick-options.less
=> Added flex without shrink to modal pick sections. Header text now is black

js/components/cohort-comparison-manager.html, js/components/cohort-definition-browser.js, js/components/cohort/linked-cohort-list.html, js/components/cohort/linked-cohort-list.js, js/components/cohort/linked-cohort-list.less, js/components/faceted-datatable.html, js/components/linked-entity-list.html, js/components/linked-entity-list.js, js/components/linked-entity-list.less, js/components/modal.html, js/components/modal.js, js/components/modal.less, js/components/plp-spec-editor.html, js/components/tabs.html, js/components/tabs.js, js/components/tabs.less, js/components/visualizations/filter-panel/utils.js, js/pages/cohort-definitions/cohort-definitions.html, js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html, js/pages/incidence-rates/components/iranalysis/components/editor.html, js/pages/vocabulary/components/import.html, js/pages/vocabulary/components/search.html, js/pages/vocabulary/components/search.js, js/pages/vocabulary/routes.js, js/pages/vocabulary/vocabulary.html, js/pages/vocabulary/vocabulary.js
New components for https://github.com/OHDSI/WebAPI/issues/495 and https://github.com/OHDSI/WebAPI/issues/522. Usage samples can found in https://github.com/OHDSI/Atlas/tree/new-cohort-characterization
=> New components: Linked entity list, Linked cohort list, Modal. Improved Tabs component.

js/pages/incidence-rates/components/iranalysis/components/editor.html, js/pages/incidence-rates/components/iranalysis/components/editor.js, js/pages/incidence-rates/ir-manager.html
Fixed permission checks on Incidence Rates page. Closes https://github.com/OHDSI/Atlas/issues/801
=> Fixed permission checks on Incidence Rates page

js/pages/cohort-definitions/components/reporting/cost-utilization/base-report.js
(cherry picked from commit 7143967)
=> Fixed value=NULL handling for Cost & Util charts

js/app.less
=> added height to a backdrop

js/components/cohortbuilder/AdditionalCriteria.js, js/components/cohortbuilder/InputTypes/Window.js, js/components/cohortbuilder/components/CriteriaGroup.js, js/components/cohortbuilder/components/CriteriaGroupTemplate.html, js/components/cohortbuilder/components/CycleToggleInputTemplate.html, js/components/cohortbuilder/css/builder.css, js/components/cohortbuilder/options.js, js/components/cohortdefinitionviewer/components/CriteriaGroupTemplate.html, js/pages/cohort-definitions/cohort-definition-manager.js
Depends on issue-51 branch of circe-be in order to translate the new options to sql.
=> Allow users to cycle start/end of index date.

js/main.js, js/pages/configuration/routes.js
=> Fixed wrong import in Data source configuration screen

js/modules/databindings/datatableBinding.js, js/pages/configuration/sources/source-manager.js, js/settings.js
Fixes OHDSI/WebAPI#496
- Fixed missed table button for column visibility
=> Fixed Missed job names

js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/cohort-definitions/components/reporting/cost-utilization/base-drug-util-report.js, js/pages/cohort-definitions/components/reporting/cost-utilization/base-report.js, js/pages/cohort-definitions/components/reporting/cost-utilization/visit-util.html, js/pages/cohort-definitions/components/reporting/cost-utilization/visit-util.js
fixes https://github.com/OHDSI/Atlas/issues/834
fixes https://github.com/OHDSI/Atlas/issues/835
=> UX improvements for Cost & Util reports

js/modules/databindings/datatableBinding.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/cohort-definitions/const.js, js/settings.js
closes https://github.com/OHDSI/Atlas/issues/836
=> Added ability to select whether rollups should be enabled for Cost & Util reports

js/components/conceptset/conceptset-manager.html, js/components/conceptset/conceptset-manager.js, js/components/conceptsetInclusionCount/conceptsetInclusionCount.html, js/components/conceptsetInclusionCount/conceptsetInclusionCount.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/services/ConceptSet.js
=> Added Lazy loading inclusion concept counts

js/components/home.js
fixes https://github.com/OHDSI/Atlas/issues/844
=> Shorten timeout for GitHub issues load query

js/pages/configuration/users-import/users-import.html, js/pages/configuration/users-import/users-import.js, js/pages/configuration/users-import/users-import.less, js/services/User.js
1. Added connection test before import
2. Added help for user mapping columns
sorry for using jquery click handlers, but don't see another way to resolve that
=> Users import improvements

js/pages/cohort-definitions/cohort-definition-manager.js
=> Dereference conceptSetDirtyFlag.

js/components/concept-manager.html, js/components/concept-manager.js, js/pages/profiles/profile-manager.html, js/pages/profiles/profile-manager.js, js/pages/vocabulary/components/search.html, js/pages/vocabulary/components/search.js
Fixed 'this' reference in profile manager.
Use 'ageAtIndex' to show date of person.
Fixed links in Herarchy tab.
Applied colorizeLink in search results view.
=> Profile manager and Concept View fixes

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/profiles/profile-manager.js, js/styles/atlas.css
=> Cohort reporting bug fix

js/pages/data-sources/classes/Treemap.js, js/pages/data-sources/components/reports/condition.js, js/pages/data-sources/components/reports/conditionEra.js, js/pages/data-sources/components/reports/drug.js, js/pages/data-sources/components/reports/drugEra.js, js/pages/data-sources/components/reports/measurement.js, js/pages/data-sources/components/reports/observation.js, js/pages/data-sources/components/reports/procedure.js, js/pages/data-sources/components/reports/visit.js
Fixes https://github.com/OHDSI/Atlas/issues/863
=> Fixed column names in Achilles treemap reports

js/pages/data-sources/classes/Report.js, js/pages/data-sources/components/reports/achillesHeel.html, js/pages/data-sources/components/reports/achillesHeel.js, js/pages/data-sources/components/reports/dashboard.html, js/pages/data-sources/components/reports/dashboard.js, js/pages/data-sources/components/reports/datadensity.html, js/pages/data-sources/components/reports/datadensity.js, js/pages/data-sources/components/reports/death.html, js/pages/data-sources/components/reports/death.js, js/pages/data-sources/components/reports/person.html, js/pages/data-sources/components/reports/person.js, js/pages/data-sources/components/reports/treemap.html, js/pages/data-sources/components/reports/treemapDrilldown.js, js/pages/data-sources/data-sources.html
fixes https://github.com/OHDSI/Atlas/issues/864
=> Fixed Achilles report data reload on DS change

js/modules/conceptsetbuilder/components.js, js/modules/conceptsetbuilder/components/ConceptSetBuilder.js, js/modules/conceptsetbuilder/components/ConceptSetBuilderTemplate.html
=> fixed modal for loading concept sets in incidence rates analyses

js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed multiple polling of cohort generation info

js/modules/WebAPIProvider/AuthAPI.js, js/pages/incidence-rates/components/iranalysis/components/browser.html, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js
=> Fixed permission checks for IR (copy, delete)

js/pages/configuration/sources/source-manager.html, js/pages/configuration/sources/source-manager.js
=> Fix renaming of Datasource key

js/pages/home/routes.js
Hi Anthony @anthonysena, please review. This is for issue 896. Thank you!
=> For issues 896 => fix authApi not defined error after authentication.

index.html, js/styles/atlas.css, js/styles/splash.css
=> moved splash screen related css

js/modules/databindings/chart.js, js/pages/data-sources/data-sources.html, js/pages/data-sources/routes.js
closes #914 
also need improvements into @ohdsi/atlascharts package
=> fixed exception on charts (bad data)

.gitignore, js/components/terms-and-conditions/terms-and-conditions.js, js/config.js, js/config/app.js, js/config/terms-and-conditions.js, js/main.js, js/settings.js
This removes the multiple -local config files in place of a single root config module which is constructed from sub-config files.
The config-local file is the single source of configuration overrides.
=> Refactor configuration files.

js/pages/configuration/routes.js, js/pages/configuration/sources/source-manager.js
Fixed empty (without any fields) new data source page (after opening existed data source) https://github.com/OHDSI/WebAPI/issues/577
=> Fixed empty new data source page

js/pages/configuration/routes.js, js/pages/configuration/sources/source-manager.js
Fixed empty (without any fields) new data source page (after opening existed data source) https://github.com/OHDSI/WebAPI/issues/577
=> Fixed empty new source page

js/pages/configuration/users-import/users-import.js
Fixes https://github.com/OHDSI/WebAPI/issues/613
=> Fixed AD import issues

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js, js/pages/data-sources/classes/Treemap.js, js/pages/data-sources/components/reports/dashboard.js, js/pages/data-sources/components/reports/person.js, js/pages/data-sources/components/reports/treemapDrilldown.js, js/settings.js, js/utils/ChartUtils.js
Fixes https://github.com/OHDSI/Atlas/issues/938
=> Fixed age of observation chart with negative ages

js/pages/configuration/configuration.js, js/pages/configuration/roles/role-details.js
Fixes https://github.com/OHDSI/WebAPI/issues/618
=> Fixed permissionIds and roleIds evaluation

js/modules/databindings/datatableBinding.js, js/pages/pathways/components/manager.js, js/pages/pathways/components/tabs/pathway-results.html, js/providers/Model.js
=> Pathway fixes

js/pages/cohort-definitions/cohort-definition-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/964
=> Less frequent cohort generation status polling

js/modules/WebAPIProvider/SourceAPI.js
Fixes https://github.com/OHDSI/Atlas/issues/973
=> Fixed source ordering

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/home/home.html, js/pages/home/home.js, js/settings.js
These are the final changes for the 2.6.0 release of Atlas.
=> Release Candidate 2.6.0

js/pages/characterizations/services/CharacterizationService.js, js/pages/pathways/PathwayService.js
Fixes https://github.com/OHDSI/Atlas/issues/1001
=> Extended limit for Pathways and CCs until proper work with server-side pagination is implemented

js/pages/estimation/PermissionService.js, js/pages/estimation/cca-manager.js, js/pages/estimation/estimation-browser.html, js/pages/estimation/estimation-browser.js, js/pages/prediction/PermissionService.js, js/pages/prediction/prediction-browser.html, js/pages/prediction/prediction-browser.js, js/pages/prediction/prediction-manager.js, js/services/Estimation.js, js/services/Prediction.js
Front-end fix for https://github.com/OHDSI/WebAPI/issues/642
Fixes https://github.com/OHDSI/Atlas/issues/1009
Fixes https://github.com/OHDSI/Atlas/issues/1010
Fixes https://github.com/OHDSI/Atlas/issues/983
=> Fixes UI security methods. Fixes PLE / PLP update & download methods

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/providers/Model.js, js/utils/DatatableUtils.js
=> added status canceled to cohort generation page

js/pages/jobs/job-manager.js
=> Removed default end date for job

js/components/cohortdefinitionviewer/components/ConceptSetViewer.js, js/components/cohortdefinitionviewer/components/ConceptSetViewer.less, js/components/cohortdefinitionviewer/components/ConceptSetViewerTemplate.html, js/components/cohortdefinitionviewer/main.js
=> Fixes for performance of Cohort - Export (text view) tab

js/pages/configuration/roles/role-details.js
Fixes https://github.com/OHDSI/Atlas/issues/1022
=> Added refresh for permissions

js/pages/configuration/const.js, js/pages/configuration/sources/source-manager.js
Part of https://github.com/OHDSI/WebAPI/issues/587
=> Restrict deletion of sources with top-priority daimons

js/components/modal.html, js/components/modal.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/concept-sets/conceptset-manager.less
Fixes https://github.com/OHDSI/Atlas/issues/1029
=> Fixes frozen modal backdrop after page navigation

js/pages/concept-sets/conceptset-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/1027
=> Fixed blocking popup shadow remaining after saving new optimized concept set

js/components/source-manager.js
Part of https://github.com/OHDSI/WebAPI/issues/587 for 2.4.5
=> Restrict deletion of sources with top-priority daimons into 2.4.5

js/modules/WebAPIProvider/SourceAPI.js, js/pages/configuration/const.js, js/pages/configuration/sources/source-manager.js
Part of https://github.com/OHDSI/WebAPI/issues/587 for 2.5.2
=> Restrict deletion of sources with top-priority daimons into 2.5.2

js/pages/cohort-definitions/cohort-definition-manager.js, js/utils/CommonUtils.js
Fixes https://github.com/OHDSI/Atlas/issues/1024
=> Fixed incorrect link to cohort definition generated by UI

js/pages/cohort-definitions/cohort-definition-manager.html, js/styles/atlas.css
Fixes https://github.com/OHDSI/Atlas/issues/1045
=> [v.2.5.2] Moved readonly parameter to separate class

js/components/cohort-definitions/cohort-definition-manager.html, js/styles/atlas.css
Fixes https://github.com/OHDSI/Atlas/issues/1045
=> [v.2.4.5] Moved readonly parameter to separate class

js/pages/concept-sets/concept-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/969
=> Fixed loading counts on "Record counts" tab

package.json
=> Fixed bundle build

js/components/terms-and-conditions/terms-and-conditions.js
=> Fixed T&C popup

js/Model.js
Was ignored during work on
https://github.com/OHDSI/Atlas/issues/1018
=> Brought back logging for not found concepts

js/config.js
=> updated to correct configuration file name in warning

js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixes #1036 - Concept set saving from inside cohort results in empty concept set

js/services/JobDetailsService.js
Instead of https://github.com/OHDSI/WebAPI/pull/684
Closes https://github.com/OHDSI/Atlas/issues/1082
=> Store last viewed time in local storage for insecure mode

js/pages/incidence-rates/ir-manager.js
Fixes https://github.com/OHDSI/WebAPI/issues/677
=> Fixed typo in 'JobDetailsService'

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
Fixes https://github.com/OHDSI/Atlas/issues/1061
=> Rounded 'avg' and 'stdDev' for cohort characterization

js/pages/configuration/sources/source-manager.html
Fixes https://github.com/OHDSI/WebAPI/issues/513
=> Improved warning messages for Source configuration

js/pages/concept-sets/concept-manager.html, js/pages/concept-sets/concept-manager.js, js/pages/concept-sets/routes.js
Fixes https://github.com/OHDSI/Atlas/issues/1063
=> Set 'loadingRelated' in proper places while browsing vocabulary hierarchy

js/components/cohortbuilder/components/CohortExpressionEditor.js, js/components/cohortbuilder/components/CohortExpressionEditor.less, js/components/cohortbuilder/components/CohortExpressionEditorTemplate.html
Fixes https://github.com/OHDSI/Atlas/issues/1088
=> Fixed markup for Cohort Definition - Inclusion rules

js/app.less
Fixes https://github.com/OHDSI/Atlas/issues/878
Instead of https://github.com/OHDSI/Atlas/pull/1069/files
Tagging @fdefalco , @chrisknoll
=> Added adaptive layout for navbar

js/assets/ohdsi.util.js
Fixes https://github.com/OHDSI/Atlas/issues/1018
=> Fixed dirtyFlag for nested null values

js/pages/cohort-definitions/cohort-definition-manager.html
Fixes https://github.com/OHDSI/Atlas/issues/1114
Tooltip was not shown because the button was disabled
=> Fixed absence of "not enough permissions" tooltip

js/components/DropDownMenu.html, js/components/DropDownMenu.js, js/components/cohortbuilder/WindowedCriteria.js, js/components/cohortbuilder/components.js, js/components/cohortbuilder/components/CriteriaGroup.js, js/components/cohortbuilder/components/CriteriaGroupTemplate.html, js/components/cohortbuilder/components/DemographicCriteria.js, js/components/cohortbuilder/components/WindowedCriteria.html, js/components/cohortbuilder/components/WindowedCriteria.js, js/components/cohortbuilder/components/WindowedCriteria.less, js/components/cohortbuilder/components/const.js, js/components/cohortbuilder/components/utils.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.less
Implements stage 1 from https://github.com/OHDSI/WebAPI/issues/495#issuecomment-412667979
=> Implements distribution criteria analyses for Cohort Characterization

js/components/cohort/linked-cohort-list.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html
=> Fixed pointer style for links in Cohort Characterization

js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js
=> Fixed display of name in Concept Set header

index.html, js/app.js, js/app.less, js/detectBrowser.js, js/main.js, js/styles/atlas.css, js/styles/browserWarning.css, js/utils/BrowserDetection.js
Fixes https://github.com/OHDSI/Atlas/issues/1091
=> Added browser check bar on top of the window [v.2.4.5]

js/const.js, js/pages/concept-sets/concept-manager.js
=> Fixed reloading of the data in Concept Manager

js/app.js, js/components/atlas-state.js, js/components/cohort-definitions/const.js, js/components/configuration.js, js/components/source-manager.js, js/const.js, js/main.js, js/modules/WebAPIProvider/SourceAPI.js, js/modules/WebAPIProvider/VocabularyProvider.js, js/modules/conceptpicker/ConceptPicker.js
Fixes https://github.com/OHDSI/Atlas/issues/1101
=> Fixed observables for source-manager

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less
- Fixed chaotic columns width in CC results
- Removed not reachable code
=> Fixed chaotic columns width in CC results

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.html, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.less
Added explore prevalence with stratas as part of #1078
=> Added explore prevalence with stratas

js/pages/concept-sets/concept-manager.js, js/pages/concept-sets/const.js
Covers item 2 from https://github.com/OHDSI/Atlas/issues/1178. Related to https://github.com/OHDSI/WebAPI/issues/649
=> Show Concept Hierarchy for all vocabs, not only pre-defined

js/Model.js
=> Added prompt regarding unsaved CC on page reload

js/pages/characterizations/components/characterizations/CharacterizationAnalysis.js, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/configuration/roles/role-details.html, js/pages/configuration/roles/role-details.js, js/pages/configuration/sources/source-manager.html, js/pages/configuration/sources/source-manager.js, js/pages/configuration/users-import/job-view-edit.html, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/components/iranalysis/IRAnalysisDefinition.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/PathwayAnalysis.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js, js/styles/atlas.css
Fixes https://github.com/OHDSI/WebAPI/issues/341
=> Added conditions to enable save button

js/components/conceptsetInclusionCount/conceptsetInclusionCount.js
=> Fixed multiple count requests on concept set page

js/components/cohortbuilder/components/FeasibilityAttritionReport.js, js/components/featureextraction/components/CovariateSettingsEditor.html, js/extensions/bindings/numericExtender.js
=> Use d3.scaleThreshold() for color classification.

js/extensions/bindings/htmlValueBinding.js
@chrisknoll @johnSamilin 
Fixed OHDSI/WebAPI#382 XSS problem for concept name by applying the note of PR #1166
=> Retouched concept name XSS issue..

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/characterizations/const.js, js/pages/estimation/cca-manager.js, js/styles/atlas.css
Fixes https://github.com/OHDSI/WebAPI/issues/728
=> Aligned Feature Analysis header

js/Model.js, js/components/evidence/components/negative-controls.js, js/components/user-bar.js, js/const.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/cohort-definitions/components/checks/conceptset-warnings.js, js/pages/concept-sets/conceptset-manager.js, js/services/CDMResultsAPI.js
This PR addresses a number of bugs as described in each commit message. Specifically:
#1200 - User bar permission warning
#1201 - Remove circular dependency for const.js
#1202 - Concept Set will not load
#1205 - Cohort generation polling
#1206 - Dispose of cohort warning subscription
Also, there is a commit for fixes related to negative controls which I did not log but am happy to do that if needed.
=> Various issues fixed

js/settings.js, package.json
=> resolved npm warning for deprecated license metadata

js/components/conceptsetInclusionCount/conceptsetInclusionCount.js
=> Fixed multiple count requests

js/pages/characterizations/components/characterizations/characterization-view-edit.js
=> Fixed exception when re-opening characterization

js/components/welcome.js
Fixes https://github.com/OHDSI/Atlas/issues/1216
=> Fixed authentication for providers without explicit login form

js/pages/pathways/components/manager.js
Fixed #1214 
The function to be called is located below the called function.
In addition to CC (Characterizations), the same bugs in Pathways have been fixed at the same time.
=> Fixed load cc caption bug and pathways..

js/Model.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
Fixes https://github.com/OHDSI/WebAPI/issues/263
=> Added message for not existing cohort

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> added check for initial event before generating

js/pages/data-sources/data-sources.js, js/utils/CommonUtils.js
Fixes https://github.com/OHDSI/WebAPI/issues/720
=> Used DS with result & vocabulary daimons for Data Source tab

js/pages/configuration/sources/source-manager.js
Fixes https://github.com/OHDSI/WebAPI/issues/683
=> Added message after failed DS saving

index.html, js/Model.js
Removed redundant computed var
=> Cleanup redundant computed variable for #898

js/components/cohortbuilder/components/FeasibilityAttritionReport.html, js/components/cohortbuilder/components/FeasibilityIntersectReport.html
=> Fix inclusion impact report where censor period is being used

package.json
=> fixed resize issue

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/pathways/components/tabs/pathway-executions.js
=> fixed check of the current state of the generation

js/extensions/bindings/datatableBinding.js
=> fixed sorting for cases when one date is empty

js/pages/pathways/components/browser.js
Fixes https://github.com/OHDSI/WebAPI/issues/763
=> Showed created and updated dates for Cohort Pathways

js/pages/cohort-definitions/cohort-definition-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1225
=> added forgotten import

js/components/cohort-comparison-browser.js, js/components/cohort-definition-browser.js, js/components/job-manager.js, js/components/plp-browser.js, js/modules/WebAPIProvider/MomentAPI.js, js/modules/circe/components/CohortConceptSetBrowserTemplate.html, js/modules/databindings/datatableBinding.js, js/pages/incidence-rates/components/iranalysis/components/browser.js
=> 2.5.2 table sorting

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/pathways/components/tabs/pathway-executions.js
fixes https://github.com/OHDSI/Atlas/issues/1215
+ fixes some observables
=> Fixed stat type selection in Feature Analysis

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js
fixes https://github.com/OHDSI/Atlas/issues/1244
=> Fixed removal of stratas from CC

js/Model.js, js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/components/tabs/included-sourcecodes.js, js/services/ConceptSet.js
fixes https://github.com/OHDSI/Atlas/issues/1262
=> Fixes for Concept set ancestors load

js/pages/characterizations/components/feature-analyses/const.js
fixes https://github.com/OHDSI/Atlas/issues/1270
=> Add created / modified metadata to Feature Analyses

js/services/Poll.js, js/settings.js, package.json
Removed visibility.core from package.json in order to change the implementation.
=> Make visibility.core.js AMD compatable.

js/pages/vocabulary/components/search.js
Fixes https://github.com/OHDSI/Atlas/issues/1266
=> Fixed typo in variable

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/1255
=> Fixed sizes of donut charts

js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js
=> Fixes Inconsistent options when creating new entities

js/pages/cohort-definitions/components/checks/utils.js
fixes https://github.com/OHDSI/Atlas/issues/1300
=> fixes message for concept sets with 0 index

js/pages/profiles/index.js, js/pages/profiles/profile-manager.html, js/pages/profiles/profile-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/1278
=> Added conditions to hide profile blocks

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html, js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
=> fixed misuse of colorbrewer package

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
=> set fixed width to first column

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/characterizations/services/CharacterizationService.js, js/pages/pathways/PathwayService.js, js/pages/pathways/components/tabs/pathway-executions.html, js/pages/pathways/components/tabs/pathway-executions.js
=> Added cancel job execution for CC, Pathways and IR

js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/services/CharacterizationService.js, js/pages/characterizations/services/PermissionService.js, js/pages/pathways/PathwayService.js, js/pages/pathways/PermissionService.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js
=> Added ability to copy cohort characterizations and pathway analyses

js/pages/cohort-definitions/cohort-definition-manager.js, js/services/Poll.js
=> Fixed polling issues

js/styles/atlas.css
=> Added horizontal scroll on the main viewport

js/app.less, js/styles/atlas.css
=> Applied a `scroll-y` style on the left nav container to scroll as needed

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
=> fixed possible co-variate name conflict

js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/1322
=> Added conditions to disable header buttons

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
=> Fixed exception in data completeness report

js/assets/ohdsi.util.js, js/components/conceptpicker/ConceptPickerTemplate.html, js/components/conceptsetbuilder/components/ConceptSetBuilderTemplate.html, js/extensions/bindings/childChangesExtender.js, js/extensions/bindings/main.js
=> Fixed change detection on children update

js/Model.js
Fixes https://github.com/OHDSI/Atlas/issues/883
=> Removed case for backwards compatibility for person count

js/Model.js, js/components/conceptsetInclusionCount/conceptsetInclusionCount.js, js/pages/concept-sets/components/tabs/included-conceptsets.html, js/pages/concept-sets/components/tabs/included-conceptsets.js
fixes https://github.com/OHDSI/WebAPI/issues/737
=> fixed Confusing Included Concepts count

js/components/welcome.js, js/pages/configuration/sources/source-manager.html, js/pages/configuration/sources/source-manager.js, js/services/AuthAPI.js
=> Fixed missing loaders

js/pages/data-sources/components/reports/death.js
=> Fixed death prevalence by month precision

js/components/faceted-datatable.js, js/pages/characterizations/components/feature-analyses/feature-analyses-browser.html, js/pages/characterizations/components/feature-analyses/feature-analyses-browser.js
=> Fixed 'select all' for filtered feature analyses

js/components/ac-access-denied.html, js/components/ac-access-denied.js, js/components/ac-access-denied.less, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html, js/pages/characterizations/components/tabbed-grid.html, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definitions.html, js/pages/configuration/configuration.html, js/pages/configuration/roles/roles.html, js/pages/configuration/sources/source-manager.html, js/pages/configuration/users-import/browser.html, js/pages/configuration/users-import/browser.js, js/pages/configuration/users-import/job-view-edit.html, js/pages/configuration/users-import/users-import.html, js/pages/data-sources/data-sources.html, js/pages/incidence-rates/ir-browser.html, js/pages/pathways/components/browser.html
fixes https://github.com/OHDSI/Atlas/issues/917
=> Refactored access denied panel to remove extra code

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js
=> added promt

js/extensions/bindings/alphaNumericExtender.js, js/extensions/bindings/main.js, js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
Enforces an alphanumeric when defining the R package name.
=> Fixes #1170 - valid package name enforcement

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
fixes https://github.com/OHDSI/Atlas/issues/1194
fixes https://github.com/OHDSI/Atlas/issues/1313
=> Fixes data display for comparative CC

js/components/cohortbuilder/components/InclusionRuleEditor.js, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js
Fixes https://github.com/OHDSI/Atlas/issues/1291
=> Added checking for Strata names

js/components/conceptpicker/ConceptPicker.js, js/pages/configuration/configuration.html, js/pages/configuration/configuration.js, js/pages/profiles/profile-manager.html, js/pages/profiles/profile-manager.js, js/services/AuthAPI.js, js/services/SourceAPI.js, js/services/Vocabulary.js
fixes https://github.com/OHDSI/WebAPI/issues/846
- Fixed loading state of Concept Picker
- Display Access denied label in Config screen for Sources which user doesn't have access to
- Display only granted Sources in Profile viewer
- Fixed resolution of default diamons to respect permissions
- Refactor sources retrieval for Vocabulary service
=> Several security fixes. Fixed loading state of Concept Picker. Refactoring of Vocabulary service

js/components/cohort-comparison-manager.html, js/components/cohort-comparison-manager.js, js/components/plp-manager.html, js/components/plp-manager.js, js/modules/WebAPIProvider/ExecutionAPI.js
fixes download results of PLP/PLE
=> fix for PLP/PLE execution results

js/pages/characterizations/components/characterizations/characterizations-list.html, js/pages/characterizations/components/feature-analyses/feature-analyses-list.html, js/pages/characterizations/components/tabbed-grid.html
Small change to properly pass the function and not the value.
fixes #1355
=> Fixes #1355 - Cohort Characterization List Throws Error

js/pages/concept-sets/conceptset-manager.js
=> Fixes #1307 - Unique concept set names

js/Application.js, js/config/app.js, js/main.js
fixes https://github.com/OHDSI/WebAPI/issues/709
=> Added github oauth support(WebAPI #709)

js/pages/cohort-definitions/cohort-definition-manager.js, js/services/CohortDefinition.js
fix #1013 
see also https://github.com/OHDSI/WebAPI/pull/853
=> Added error message in case of deleting cohort which is used in pathway (#1013)

js/pages/pathways/components/tabs/pathway-executions.js
fix #1358 
see also https://github.com/OHDSI/WebAPI/pull/850
=> added notification creation on cohort pathway generation(#1358)

js/components/user-bar.js, js/services/AuthAPI.js
fixes https://github.com/OHDSI/Atlas/issues/1377
=> Fixed loading of Notifications list

js/components/cohort-comparison-manager.js
=> Fixes Estimation import that was not work

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Added button to copy analysis sql template to clipboard

js/components/cohortbuilder/components/DemographicCriteriaTemplate.html
=> Fixed markup issue with Criteria attribute selector in Feature Analysis

js/pages/data-sources/components/reports/datadensity.js
=> Issue 1280 data sources density plots

js/components/Chart.js, package.json
=> Dispose chart when component is disposed.

js/pages/data-sources/components/reports/treemapDrilldown.js
=> Fixed tooltip in Frequency Distribution plot

js/pages/data-sources/components/reports/person.js
=> Fixed tooltip in Person YearofBirth plot

js/pages/incidence-rates/components/iranalysis/components/results.js
=> Fixed selection of disabled DSs in IR generation popup

js/components/generation/select-sources-btn.js, js/pages/incidence-rates/components/iranalysis/components/results.js
=> added cohort count check for IR

js/components/cohortbuilder/components/EndStrategyEditor.js
=> Handle event persistence dropdown after import.

js/pages/characterizations/components/characterizations/CharacterizationAnalysis.js
fixes https://github.com/OHDSI/WebAPI/issues/894
=> Fixed update of CC

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js
fixes https://github.com/OHDSI/Atlas/issues/1408
to be merged after https://github.com/OHDSI/WebAPI/issues/894
=> Prohibit duplication of strata names in CC

js/components/user-bar.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/estimation/components/cca-executions.js, js/pages/pathways/components/tabs/pathway-executions.js, js/pages/prediction/components/prediction-executions.js, js/services/Poll.js
related to https://github.com/OHDSI/WebAPI/issues/879
=> [WIP] Changed polling service to use setTimeout function

js/pages/characterizations/services/PermissionService.js, js/pages/estimation/cca-manager.js, js/pages/pathways/PermissionService.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js
=> Making Characterization / Pathways consistent with other type of analyses

js/components/utilities/export.html, js/components/utilities/export.js, js/components/utilities/export.less, js/components/utilities/import.html, js/components/utilities/import.js, js/components/utilities/import.less, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.less, js/pages/estimation/PermissionService.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/estimation/components/cca-utilities.html, js/pages/estimation/components/cca-utilities.js, js/pages/estimation/const.js, js/pages/estimation/routes.js, js/pages/prediction/PermissionService.js, js/pages/prediction/components/prediction-utilities.html, js/pages/prediction/components/prediction-utilities.js, js/pages/prediction/const.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js, js/pages/prediction/routes.js, js/services/Estimation.js, js/services/Prediction.js, js/settings.js, js/utils/DataTypeConverterUtils.js
Corresponding front-end changes for https://github.com/OHDSI/WebAPI/pull/861 and https://github.com/OHDSI/StandardizedAnalysisAPI/pull/17 to address #1335.
Some notes on the changes:
- Created shared components for import/export based off of the CC approach. These are now utilized by CC, Estimation & Prediction. 
- Made a small fix to `js/pages/characterizations/components/characterizations/characterization-view-edit.js` since it wouldn't properly redirect the newly imported specification since the condition evaluation wasn't correct. 
Again, these changes can wait until we're done with https://github.com/OHDSI/WebAPI/pull/861 which depends on https://github.com/OHDSI/WebAPI/pull/845
=> Import PLE and PLP. Fixes #1335

js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js, js/pages/incidence-rates/components/iranalysis/components/results.less, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/services/IRAnalysis.js
=> Fixes IR allows running even if previous execution is not completed yet

js/pages/prediction/inputTypes/ModelSettings.js
Discovered an incorrect default for decision tree model settings.
=> Fix default for decision tree model settings

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js
=> Renamed strata to subgroup in characterizations

js/components/generation/select-sources-popup.html, js/components/generation/select-sources-popup.js
=> Added pagination to ir sources table

js/app.less
=> Fixed z-index for modal-overlay

js/pages/concept-sets/components/conceptsets-export.js
=> Fixed export of concept cet

js/pages/estimation/const.js
Changed to properly deference observable properties.
=> Fix estimation ps adjustment strategy display - Fixes #1445

js/pages/configuration/sources/source-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1455
=> Fixed deletion of Data source (2.7)

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1452
=> Fixed permissions checking for persisting new PLE/PLP

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1452
=> Fixed permissions checking for persisting new PLE/PLP (2.7)

js/pages/configuration/sources/source-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1455
=> Fixed deletion of Data source

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/services/conversion/BaseStatConverter.js, js/pages/characterizations/services/conversion/PrevalenceStat.js, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
=> Adds concept code to cc results

js/extensions/bindings/profileChart.js
fixes https://github.com/OHDSI/Atlas/issues/1461
=> Fixed Profiles strict mode

js/extensions/bindings/profileChart.js
fixes https://github.com/OHDSI/Atlas/issues/1461
=> Fixed Profiles strict mode (#1462)

js/extensions/bindings/profileChart.js
fixes https://github.com/OHDSI/Atlas/issues/1463
=> Fixes tooltips in Profiles page

js/pages/cohort-definitions/cohort-definition-manager.js
=> Enforce including 'UseEventEnd' in exported JSON.

js/pages/Router.js
=> Issue 1473 not authed active menu item

js/pages/concept-sets/concept-manager.html, js/pages/concept-sets/concept-manager.js, js/pages/concept-sets/conceptset-browser.html, js/pages/concept-sets/conceptset-browser.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/estimation/estimation-browser.html, js/pages/estimation/estimation-browser.js, js/pages/incidence-rates/ir-browser.js, js/pages/jobs/job-manager.html, js/pages/prediction/prediction-browser.html, js/pages/prediction/prediction-browser.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js, js/pages/vocabulary/PermissionService.js, js/pages/vocabulary/components/search.html, js/pages/vocabulary/components/search.js
=> fixed permissions checks

js/const.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js
=> Added pending state to generation button on characterization page

js/pages/incidence-rates/const.js, js/pages/incidence-rates/ir-browser.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/incidence-rates/routes.js
Fixes Error page after IR deletion
=> ATLP-642 Error page after IR deletion

js/pages/concept-sets/components/tabs/conceptset-compare.js
=> Fixed endless loader in compare cs table header

js/pages/vocabulary/components/search.html, js/pages/vocabulary/components/search.js
=> Fixed handcart icon in column visibility list on search page

js/services/JobDetailsService.js
Fixes https://github.com/OHDSI/Atlas/issues/1430
=> Changed finding of old job

js/styles/atlas.css
=> Fixed column visibility block on data sources page

js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
fixes https://github.com/OHDSI/Atlas/issues/1470
instead of https://github.com/OHDSI/Atlas/pull/1471
=> Fixed escaping of quotes in CC report - Concept name

package.json
fixes https://github.com/OHDSI/Atlas/issues/1477
=> Updates charts lib version to fix freezing tooltips

js/components/atlas-state.js, js/pages/concept-sets/PermissionService.js, js/pages/concept-sets/concept-manager.html, js/pages/concept-sets/concept-manager.js, js/pages/vocabulary/PermissionService.js
fixes https://github.com/OHDSI/WebAPI/issues/950
=> Fixes RC pulling for Concept

js/components/modal.less
=> fixed width of the modals

js/pages/data-sources/classes/Treemap.js, js/pages/data-sources/components/reports/treemapDrilldown.js
fixes https://github.com/OHDSI/Atlas/issues/1499
=> Fixes treemap drilldown when data source is switched

js/pages/vocabulary/PermissionService.js, js/pages/vocabulary/components/import.html, js/pages/vocabulary/components/import.js
fixes https://github.com/OHDSI/Atlas/issues/1500
=> Fixes permissions check for Concept Sets import

js/pages/pathways/components/tabs/pathway-results.html, js/pages/pathways/components/tabs/pathway-results.js, js/pages/pathways/components/tabs/pathway-results.less
=> Added modal with design on pathways results page

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.js, js/pages/pathways/components/manager.js, js/pages/pathways/components/tabs/pathway-utils.html, js/pages/pathways/components/tabs/pathway-utils.js
Fixes https://github.com/OHDSI/Atlas/issues/1497
=> Fixed condition while loading pathway design

js/pages/incidence-rates/ir-manager.js
fixes https://github.com/OHDSI/Atlas/issues/1510
=> Reduces amount of IR polling requests. Excludes polling of results for non authorized Sources

js/components/welcome.html, js/components/welcome.js, js/services/AuthAPI.js
fixes https://github.com/OHDSI/WebAPI/issues/968
=> Fixes Google IAP session refresh. Add Google IAP logout

js/components/generation/select-sources-popup.js, js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/ir-manager.js
=> closes Atlas-1507 Incidence Rate Generation errors in UI

js/pages/incidence-rates/ir-manager.js
=> Fixed IR Analysis reset to new instance

js/components/conceptpicker/ConceptPicker.js, js/components/conceptpicker/ConceptPickerTemplate.html, js/components/conceptpicker/conceptpicker.less, js/components/conceptpicker/css/conceptpicker.css, js/components/conceptsetbuilder/components/IncludedConcepts.js, js/components/conceptsetbuilder/components/MappedConcepts.js, js/services/Vocabulary.js
=> Fixed typerror on concept set tab of new ir page

js/pages/pathways/components/tabs/pathway-executions.html, js/pages/pathways/components/tabs/pathway-executions.js
=> Added pending state to generation button on pathways page

js/pages/configuration/roles/role-details.html, js/pages/configuration/roles/role-details.js, js/pages/configuration/roles/role-import.html, js/pages/configuration/roles/role-import.js, js/pages/configuration/roles/role-import.less, js/pages/configuration/roles/roles.html, js/pages/configuration/roles/roles.js, js/pages/configuration/routes.js, js/settings.js, package.json
=> Issue 1269 role definition in atlas   copy existing roles to new

js/pages/configuration/roles/role-import.js
fixes https://github.com/OHDSI/Atlas/issues/1566
=> Fixed build

js/pages/data-sources/components/reports/datadensity.js
=> Fixed precision on data density plots

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js
fixes https://github.com/OHDSI/Atlas/issues/1494
=> Issue 1494 regenerate warning update

js/pages/vocabulary/components/import.html
fixes https://github.com/OHDSI/Atlas/issues/667
=> enabling import for open concept set

js/styles/atlas.css
fixes https://github.com/OHDSI/Atlas/issues/1491
=> update width button-collection

js/pages/profiles/profile-manager.js
=> fixed event highlighting

js/components/user-bar.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/estimation/components/cca-executions.js, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/tabs/pathway-executions.js, js/pages/prediction/components/prediction-executions.js, js/services/Poll.js
=> Fixed ir generation jobs loading

js/pages/jobs/job-manager.js
=> Fixed date columns in jobs

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less, package.json
=> added greying out rows

js/pages/incidence-rates/components/iranalysis/components/results.js
=> added 403 status handling

js/components/user-bar.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/estimation/components/cca-executions.js, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/tabs/pathway-executions.js, js/pages/prediction/components/prediction-executions.js, js/services/Poll.js
Fixes #1583
Also apply changes from https://github.com/OHDSI/Atlas/pull/1607
=> Fixed ir generation jobs loading (v.2.7.1)

js/components/cohortbuilder/components/CohortExpressionEditor.less, js/components/cohortbuilder/components/CohortExpressionEditorTemplate.html, js/styles/atlas.css
=> Fixed markup for inclusion criteria

js/pages/incidence-rates/components/iranalysis/components/results.js
=> Added 403 error handling for IR generation

js/pages/cohort-definitions/cohort-definitions.js, js/services/Vocabulary.js
fixes https://github.com/OHDSI/Atlas/issues/1591
fixes https://github.com/OHDSI/Atlas/issues/1592
=> Issue 1591 fix problem during return to datasources(pr from closed ticket 1593)

js/pages/Route.js
=> Fixed loading of permissions for IAP

js/pages/characterizations/components/characterizations/characterization-view-edit.js
=> Fixed Characterization page on return

js/pages/configuration/configuration.js, js/services/SourceAPI.js
fixes https://github.com/OHDSI/Atlas/issues/1594
=> Issue 1594 refresh configuration screen

js/Model.js, js/pages/configuration/roles/role-details.html, js/pages/configuration/roles/role-details.js, js/pages/configuration/roles/role-import.js, js/pages/configuration/roles/roles.html, js/pages/configuration/roles/roles.js, js/pages/configuration/routes.js, js/services/file.js, js/services/role.js
fixes https://github.com/OHDSI/Atlas/issues/1269
=> added export functionality

js/pages/configuration/sources/source-manager.html, js/pages/configuration/sources/source-manager.js
=> Adds Support of BQ keyfile json for authentication of EE jobs

js/pages/configuration/sources/source-manager.js, js/services/SourceAPI.js
fixes https://github.com/OHDSI/WebAPI/issues/997
=> Priority of enabled daimon is set to "1". Daimons with priority "0" are not shown as selected(https://github.com/OHDSI/WebAPI/issues/997)

js/components/circe/components/CohortConceptSetBrowser.js, js/components/circe/components/CohortConceptSetBrowserTemplate.html
=> Added loader after selecting concept set

js/components/welcome.js
fixes https://github.com/OHDSI/Atlas/issues/1620
=> Issue 1620 doesnt display null exp time

build/optimize.js, index.html, js/settings.js, package.json
=> Fixed bundle.js timeouts on decent connection

js/pages/configuration/sources/source-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/1639
=> fixed condition of setting checkbox

js/Model.js, js/pages/concept-sets/components/tabs/included-conceptsets.html, js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/components/tabs/included-sourcecodes.js
fixes https://github.com/OHDSI/Atlas/issues/1518
=> Fixes Concept Set reload when new concepts picked from vocabulary

js/pages/vocabulary/components/search.js
=> Fixes broken advance search capability in vocabulary search

js/components/cohortbuilder/AdditionalCriteria.js, js/components/cohortbuilder/components/CriteriaGroupTemplate.html
=> Expose IgnoreObservationPeriod in CriteriaGroup.

js/components/modal.less
=> Fixes modal overflow

js/pages/Page.js, js/pages/pathways/components/manager.js, js/pages/pathways/routes.js
=> Fixed switching between Pathways and IR opened analyses

js/pages/pathways/components/tabs/pathway-design.html
=> Fixes #1648 typo in pathways parameter description

js/pages/pathways/components/tabs/pathway-design.html, js/pages/pathways/components/tabs/pathway-design.less
=> added some messages

js/pages/data-sources/classes/Report.js, js/pages/data-sources/components/reports/person.html, js/pages/data-sources/components/reports/person.js, js/pages/data-sources/components/reports/person.less, js/pages/data-sources/index.js
Fixes https://github.com/OHDSI/Atlas/issues/1458
=> Changed description in DataSource person report

js/pages/incidence-rates/ir-manager.js
=> Fixed editing of IR Analysis after generation

js/pages/data-sources/components/reports/datadensity.js, js/pages/data-sources/components/reports/death.js
=> Issue 1536 box plot values wrong rounding

js/pages/data-sources/data-sources.js
=> list of datasources is now computed (#1441)

js/components/cohortbuilder/components/FeasibilityAttritionReport.html, js/components/cohortbuilder/components/FeasibilityAttritionReport.js
fixes https://github.com/OHDSI/Atlas/issues/1129
=> Issue 1129 added labels for attrition view

js/components/cohortbuilder/components/CustomEraStrategyTemplate.html, js/components/cohortbuilder/components/DateOffsetStrategyTemplate.html, js/components/cohortdefinitionviewer/components/CustomEraStrategyTemplate.html, js/components/cohortdefinitionviewer/components/DateOffsetStrategyTemplate.html
=> Fixed switching of cohort exit criteria

js/pages/characterizations/components/characterizations/characterizations-list.js, js/pages/characterizations/components/feature-analyses/const.js, js/pages/characterizations/components/feature-analyses/feature-analyses-list.html, js/pages/characterizations/components/tabbed-grid.html, js/pages/characterizations/components/tabbed-grid.js, js/pages/pathways/components/browser.html, js/pages/pathways/components/browser.js
Fixes https://github.com/OHDSI/Atlas/issues/1550
=> Added 'id' column to table

js/pages/profiles/profile-manager.js
=> Fixed profile chart changing selection of period

js/pages/profiles/profile-manager.html
fixes https://github.com/OHDSI/Atlas/issues/1558
=> Update profile message index if patient not found in cohort

js/pages/configuration/sources/source-manager.html, js/pages/configuration/sources/source-manager.js, js/services/SourceAPI.js
=> Fixed issue with BQ keyfile

js/components/welcome.html, js/components/welcome.js
=> Fixed message when session is expired for Google IAP

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/utils/Clipboard.js
fixes https://github.com/OHDSI/Atlas/issues/1547
=> Issue 1547 update export text view cohort definition

js/components/user-bar.js, js/services/JobDetailsService.js
URLs of notification hyperlinks are fixed
fixes https://github.com/OHDSI/Atlas/issues/1694
=> Fixed notification hyperlinks for CC and Pathways

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
fixes https://github.com/OHDSI/Atlas/issues/1417
=> Issue 1417 create set from characterisation result

js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js
Proportion is fixed - now it is multiplied by 100
fixes https://github.com/OHDSI/Atlas/issues/1692
=> Fixed proportion in CC - Explore (#1692)

js/components/circe/components/CohortConceptSetBrowser.js, js/components/circe/components/CohortConceptSetBrowserTemplate.html, js/components/cohort-definition-browser.js, js/pages/estimation/estimation-browser.js, js/pages/incidence-rates/components/iranalysis/components/browser.js, js/pages/pathways/components/browser.js, js/pages/prediction/prediction-browser.js
=> Use consistent createdBy formatter for analysis lists

js/pages/vocabulary/components/search.js
Fixes #1719 
Cherry-picked from https://github.com/OHDSI/Atlas/pull/1653
=> Vocabulary search - handle special characters

js/settings.js
fixes https://github.com/OHDSI/Atlas/issues/1726
=> Use local CSS file for bootstrap-select

js/components/cohort/linked-cohort-list.js
fixes https://github.com/OHDSI/Atlas/issues/1542
=> Issue 1542 update filter for editable name

js/components/cohortbuilder/CohortExpression.js
Changing attribute name to match circe-be
=> cdmVersionRange on cohort expression - fixes #1734 - v2.7.2

js/components/cohortbuilder/CohortExpression.js
Changing attribute name to match circe-be.
=> cdmVersionRange on cohort expression - fixes #1734 - master

js/services/MomentAPI.js
=> Fixed timezones for Cohort Definitions, Characterizations tables

js/pages/characterizations/components/characterizations/characterizations-list.js
=> Fixed 'updated' column in cohort characterizations

js/utils/DatatableUtils.js
=> Fixed Author column in Concept Set, Cohort Definitions, IR tables

js/components/cohortbuilder/components/CriteriaGroupTemplate.html
For merging to v2.7.2 release.
=> Show 'allow events outside observation period' option in all cases.

js/components/faceted-datatable.js, js/extensions/bindings/datatableBinding.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.less, js/pages/characterizations/components/feature-analyses/feature-analyses-browser.html, js/pages/characterizations/components/feature-analyses/feature-analyses-browser.js
=> Fixed Feature Analysis modal

js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js, js/pages/incidence-rates/const.js
Fixes https://github.com/OHDSI/Atlas/issues/1740
=> Disabled 'Rerun' button and viewing reports

js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js, js/pages/incidence-rates/const.js
Fixes https://github.com/OHDSI/Atlas/issues/1740
=> [v.2.7.2-rc] Disabled 'Rerun' button and viewing reports

js/components/faceted-datatable.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.less
=> Changed scrollCollapse option to false by default

js/config/app.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
fixes https://github.com/OHDSI/Atlas/issues/1757
=> Issue 1757 covariate table revision

js/config/app.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
fixes https://github.com/OHDSI/Atlas/issues/1757
=> Revision of Explore links in CC covariate table

js/pages/estimation/cca-manager.less, js/pages/estimation/components/editors/cohort-method-analysis-editor.html, js/pages/estimation/components/editors/outcome-model-args-editor.html
=> Fixed estimation collapsible area icon

js/services/JobDetailsService.js
=> Fixed notification link for cohort reporting

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
Fixes #1758 
Also: https://github.com/OHDSI/Visualizations/pull/46
=> Fixed characterization results scatterplot tooltip

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
Fixes #1758 
Also: https://github.com/OHDSI/Visualizations/pull/46
=> Fixed characterization results scatterplot tooltip (v2.7.2-rc)

js/services/JobDetailsService.js
=> Fixed notification link for cohort reporting - master branch

js/pages/estimation/cca-manager.less, js/pages/estimation/components/editors/cohort-method-analysis-editor.html, js/pages/estimation/components/editors/outcome-model-args-editor.html
=> Fixed estimation collapsible area icon - master branch

js/pages/incidence-rates/components/iranalysis/components/results.html
fixes https://github.com/OHDSI/Atlas/issues/1747
=> Fixes inability to remove IR generation results for user having access to the Source

js/pages/concept-sets/conceptset-manager.js, js/services/ConceptSet.js
Fixes https://github.com/OHDSI/WebAPI/issues/1100
=> Moved adding of copy prefix to backend

js/pages/concept-sets/conceptset-manager.js, js/services/ConceptSet.js
Fixes https://github.com/OHDSI/WebAPI/issues/1100
=> [v.2.7.2] Moved adding of copy prefix to backend

js/components/utilities/export.html, js/components/utilities/import.html, js/components/utilities/import.js, js/pages/incidence-rates/components/iranalysis/IRAnalysisExpression.js, js/pages/incidence-rates/components/iranalysis/components/editor.js, js/pages/incidence-rates/const.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/services/IRAnalysis.js
fixes https://github.com/OHDSI/Atlas/issues/1821. instead of https://github.com/OHDSI/Atlas/pull/1833/files
=> Use full cohort expressions in IR design export & import (2.7.2)

js/components/utilities/export.html, js/components/utilities/import.html, js/components/utilities/import.js, js/pages/incidence-rates/components/iranalysis/components/editor.js, js/pages/incidence-rates/const.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/services/IRAnalysis.js
fixes https://github.com/OHDSI/Atlas/issues/1821. instead of https://github.com/OHDSI/Atlas/pull/1833/files
=> Use full cohort expressions in IR design export & import

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/characterizations/services/CharacterizationService.js, js/pages/pathways/PathwayService.js, js/pages/pathways/components/tabs/pathway-executions.js, js/utils/ExecutionUtils.js
=> webapi-1110: generate version tags in UI for CC execution

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/characterizations/services/CharacterizationService.js, js/pages/pathways/PathwayService.js, js/pages/pathways/components/tabs/pathway-executions.js, js/utils/ExecutionUtils.js
=> Generate version tags in UI for CC and Pathways executions

js/Application.js
Removing code that was causing an error in #1850. Tested it by removing/adding concepts from within the concept set and also removing the concept set all together.
Tagging @pavgra @vlbe for awareness since I know there are some changes underway for concept sets based on #1839.
=> Simplify cohort concept set changes - fixes #1850

js/Application.js
Apply the fixes to master for #1850
=> Simplify cohort concept set changes - fixes #1850 - master

js/pages/cohort-definitions/cohort-definition-manager.css, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
Apply the same fixes to master
=> Add checks for concept set export - fixes #1853 - master

js/pages/incidence-rates/ir-manager.js
=> Fixed showing generation results in copied IR

js/pages/incidence-rates/components/iranalysis/components/editor.html
=> Added datepicker to IR Study Window

js/pages/pathways/components/tabs/pathway-results.html, js/pages/pathways/components/tabs/pathway-results.js
fixes https://github.com/OHDSI/Atlas/issues/1878
=> Do not throw exception when results for Pathways Analysis with no pathways are retrieved

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed tooltip message for cohort definition generation

js/pages/Route.js, js/pages/Router.js
fixes https://github.com/OHDSI/Atlas/issues/1733
=> added check for feedback screen for logout

js/pages/incidence-rates/components/iranalysis/components/editor.html
=> Added datepicker to IR Study Window - Master

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed tooltip message for cohort definition generation - Master

js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/conceptset-manager.js
Fixes #1865
This PR depends on https://github.com/OHDSI/Atlas/pull/1852
=> Fixed remaining modal backdrop

js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/conceptset-manager.js
=> Fixed remaining modal backdrop - Master

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Fixed prompt message when closing FA create form

js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js
fixes https://github.com/OHDSI/Atlas/issues/1879
=> added disabling method for ir export button

js/components/evidence/utils.js, js/pages/cohort-definitions/components/cohortfeatures/tableConfig/FormattingOptions.js
Update to use numeral for number formatting as suggested in this comment: https://github.com/OHDSI/Atlas/pull/1889#discussion_r292158432
=> Update to use numeral for #1888

js/components/utilities/const.js, js/components/utilities/export.html, js/components/utilities/export.js, js/components/utilities/export.less, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.js, js/pages/estimation/components/cca-utilities.html, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.js, js/pages/pathways/components/tabs/pathway-utils.html, js/pages/pathways/components/tabs/pathway-utils.js, js/pages/prediction/components/prediction-utilities.html
=> Disabled export for unsaved entities

js/components/circe/components/CohortConceptSetBrowser.js, js/components/circe/components/CohortConceptSetBrowserTemplate.html, js/components/cohort-definition-browser.js, js/pages/characterizations/components/characterizations/characterizations-list.js, js/pages/characterizations/components/feature-analyses/const.js, js/pages/characterizations/components/feature-analyses/feature-analyses-list.js, js/pages/estimation/estimation-browser.html, js/pages/estimation/estimation-browser.js, js/pages/incidence-rates/components/iranalysis/components/browser.js, js/pages/incidence-rates/ir-browser.js, js/pages/pathways/components/browser.js, js/pages/prediction/prediction-browser.html, js/pages/prediction/prediction-browser.js, js/utils/DatatableUtils.js
=> Fixes Estimation & Prediction lists default sorting column

js/pages/configuration/roles/role-details.js, js/utils/CommonUtils.js
=> adds confirmation dialog when deleting role

js/components/tabs.html, js/components/tabs.js, js/components/tabs.less, js/pages/cohort-definitions/components/reporting/cohort-reports/cohort-reports.html, js/pages/cohort-definitions/components/reporting/cohort-reports/cohort-reports.js, js/pages/cohort-definitions/components/reporting/cohort-reports/inclusion-report.js
Per discussions in https://github.com/OHDSI/Atlas/pull/1843 :
=> Nested Cohort inclusion reports under a single tab

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Fixed prompt message when closing FA create form - Master

js/components/utilities/export.html, js/components/utilities/export.js
=> Disabled export for unsaved entities - 2.7.2-rc

js/pages/Route.js, js/pages/Router.js
=> Updated check for secured routes - Master

js/Application.js, js/Model.js, js/components/atlas-state.js, js/components/conceptset/conceptset-editor.html, js/components/conceptset/conceptset-editor.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/concept-sets/components/conceptsets-list.js, js/pages/concept-sets/components/tabs/conceptset-export.html, js/pages/concept-sets/components/tabs/conceptset-export.js, js/pages/concept-sets/components/tabs/conceptset-expression.html, js/pages/concept-sets/components/tabs/conceptset-expression.js, js/pages/concept-sets/conceptset-manager.js, js/pages/concept-sets/const.js, js/services/ConceptSet.js, js/utils/CommonUtils.js
=> Fixed concept set included source codes not updated until save - Master

js/components/utilities/const.js, js/components/utilities/export.html, js/components/utilities/export.js, js/components/utilities/export.less, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-utils.js, js/pages/estimation/components/cca-utilities.html, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.js, js/pages/pathways/components/tabs/pathway-utils.html, js/pages/pathways/components/tabs/pathway-utils.js, js/pages/prediction/components/prediction-utilities.html
=> Disabled export for unsaved entities - Master

js/pages/data-sources/routes.js
=> Fixed data source reports

js/pages/data-sources/routes.js
=> Fixed data source reports - Master

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed showing of status panel when generating report

js/config/terms-and-conditions-content.html, js/config/terms-and-conditions.js, js/config/terms-and-conditions.less
=> Added HemOnc license agreement

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Removed custom 'preset' feature

js/components/cohort-definition-browser.js, js/components/cohort/linked-cohort-list.js, js/config/app.js, js/pages/cohort-definitions/cohort-definitions.js, js/pages/incidence-rates/components/iranalysis/components/browser.js, js/pages/incidence-rates/ir-browser.html, js/pages/incidence-rates/ir-browser.js, js/utils/CommonUtils.js, js/utils/DatatableUtils.js
=> Fixed escape content in links

js/components/cohort/linked-cohort-list.js, js/extensions/bindings/clickToEditBinding.js
=> Fixed issue with rendering in linked cohort list

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js, js/pages/characterizations/components/feature-analyses/const.js, js/pages/characterizations/const.js, js/pages/characterizations/services/conversion/PrevalenceStat.js, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js, js/pages/characterizations/utils.js
=> Fixed render of cc covariate name - Master

js/components/cohort-definition-browser.js, js/components/cohort/linked-cohort-list.js, js/config/app.js, js/pages/cohort-definitions/cohort-definitions.js, js/pages/incidence-rates/components/iranalysis/components/browser.js, js/pages/incidence-rates/ir-browser.js, js/utils/CommonUtils.js, js/utils/DatatableUtils.js
=> Fixed escape content in links - Master

js/components/cohort/linked-cohort-list.js, js/extensions/bindings/clickToEditBinding.js
=> Fixed issue with rendering in linked cohort list - Master

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Removed custom 'preset' feature - Master

js/config/terms-and-conditions-content.html, js/config/terms-and-conditions.js, js/config/terms-and-conditions.less
=> Added HemOnc license agreement - Master

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed showing of status panel when generating report - Master

js/components/cohort-definition-browser.js
fixes https://github.com/OHDSI/Atlas/issues/1946
=> Fixes sorting by Updated field in Cohort Definitions

js/pages/cohort-definitions/cohort-definitions.html
=> Fixed title for Cohort Definition page

js/pages/Route.js
=> Changed call from /refresh to /me endpoint in case of IAP Provider

js/Application.js
=> Fixed issue with saving concept set modification in cohort definition

js/pages/configuration/roles/role-details.js, js/pages/configuration/roles/role-import.html, js/pages/configuration/roles/role-import.js
=> Fixed import/export of roles

js/Application.js
=> Fixed issue with saving concept set modification in cohort definition - Master

js/pages/cohort-definitions/cohort-definitions.html
=> Fixed title for Cohort Definition page - Master

js/components/cohort-definition-browser.js
=> Fixes sorting by Updated field in Cohort Definitions - Master

js/pages/configuration/roles/role-details.js, js/pages/configuration/roles/role-import.html, js/pages/configuration/roles/role-import.js
=> Fixed import/export of roles - Master

js/pages/Route.js
=> Changed call from /refresh to /me endpoint in case of IAP Provider - Master

js/pages/configuration/users-import/components/role-group-mapping.html, js/pages/configuration/users-import/components/role-group-mapping.js, js/pages/configuration/users-import/components/search-group-dialog.js
=> Fixed issue with table not updated when adding group to role - Master

js/components/cohort-definition-browser.js
fixes https://github.com/OHDSI/Atlas/issues/1986
=> Fixes TZ in Cohort definitions list created / updated fields

js/Model.js, js/services/CohortDefinition.js
=> Adjust getCohortDefinition() to handle string expression.

js/components/cohortbuilder/components/ConceptSetSelectorTemplate.html, js/components/conceptpicker/ConceptPickerTemplate.html, js/components/conceptsetbuilder/components/ConceptSetBuilderTemplate.html, js/components/conceptsetmodal/conceptSetSaveModal.html, js/components/cyclops/components/control-editor.html, js/components/cyclops/components/prior-editor.html, js/components/featureextraction/components/covariate-settings-editor.html, js/components/featureextraction/components/temporal-covariate-settings-editor.html, js/extensions/bindings/datatableBinding.js, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js, js/pages/concept-sets/conceptset-manager.html, js/pages/configuration/roles/role-details.html, js/pages/configuration/sources/source-manager.html, js/pages/configuration/users-import/components/ldap-groups.html, js/pages/estimation/cca-manager.html, js/pages/estimation/components/editors/match-args-editor.html, js/pages/estimation/components/editors/positive-control-sythesis-settings-editor.html, js/pages/estimation/components/editors/stratify-args-editor.html, js/pages/incidence-rates/ir-manager.html, js/pages/pathways/components/manager.html, js/pages/prediction/components/editors/prediction-covariate-settings-editor.html, js/pages/prediction/prediction-manager.html
=> Added placeholders for input fields

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/estimation/cca-manager.js, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.js
Related to https://github.com/OHDSI/WebAPI/issues/639
=> Fixes getters for Access popups

js/pages/incidence-rates/const.js, js/pages/incidence-rates/index.js, js/pages/incidence-rates/routes.js
fixes https://github.com/OHDSI/Atlas/issues/2006
=> Fixes navigation inside IR

js/components/modal.html, js/extensions/bindings/bootstrapModal.js
=> Fixed closing modals when Escape button is pressed

js/pages/configuration/configuration.js, js/services/SourceAPI.js
Fixes https://github.com/OHDSI/WebAPI/issues/233
=> Get priority daimons from middle-tier

js/pages/configuration/sources/source-manager.js
fixes https://github.com/OHDSI/Atlas/issues/2013
=> Fixes sources creation and removal

js/pages/estimation/components/cca-specification-view-edit.html, js/pages/estimation/components/editors/cohort-method-analysis-editor.html, js/pages/estimation/components/editors/cohort-method-analysis-editor.js, js/pages/estimation/components/editors/comparison-editor.html, js/pages/estimation/components/editors/outcome-model-args-editor.html, js/pages/estimation/components/editors/outcome-model-args-editor.js, js/pages/estimation/components/editors/positive-control-sythesis-settings-editor.html, js/pages/estimation/components/editors/positive-control-sythesis-settings-editor.js, js/pages/estimation/const.js, js/pages/estimation/inputTypes/ComparativeCohortAnalysis/CreatePsArgs.js, js/pages/estimation/inputTypes/ComparativeCohortAnalysis/FitOutcomeModelArgs.js, js/pages/estimation/inputTypes/PositiveControlSynthesisArgs.js
Re-organized the estimation form per #1659 and feedback from @schuemie
=> Estimation form enhancements

js/pages/home/home.html, js/pages/home/home.js, js/services/ConceptSet.js, package.json
=> Fixed tooltip for conceptset ancestors modal link

js/pages/home/home.js
fixes https://github.com/OHDSI/WebAPI/issues/1334
=> Show issues from both WebAPI and Atlas milestones in the Latest release block

js/pages/concept-sets/components/tabs/included-sourcecodes.js
=> Fixed missing filters on included source codes tab

js/pages/profiles/profile-manager.js
=> Fixed colors rendering in events highlight datatable

js/components/user-bar.less, js/styles/atlas.css
=> Fixed issue with blinking horizontal scroll during page navigation

js/pages/cohort-definitions/cohort-definition-manager.html
Fixes for https://github.com/OHDSI/Atlas/issues/1933
- uncomment code to show message tab
=> Cohort definition message tab #1933

js/components/cohortbuilder/EndStrategies/CustomEraStrategy.js, js/components/cohortbuilder/components/CustomEraStrategy.js, js/components/cohortbuilder/components/CustomEraStrategyTemplate.html, js/components/cohortdefinitionviewer/components/CustomEraStrategyTemplate.html
Fixes #508.
Depends on Circe 1.9.0+
=> Support DaysSupplyOverride in CustomEraStrategy.

js/pages/pathways/components/tabs/pathway-results.js
=> Initialize sunburst colors based on event cohorts in design.

js/components/multi-select.html, js/components/multi-select.js
=> Delay multi-select update until dropdown closes.

js/pages/cohort-definitions/cohort-definition-manager.js
=> Concept set warning fix

README.md
=> Fix documentation links README

js/pages/configuration/users-import/browser.html, js/pages/configuration/users-import/components/job-history.js, js/pages/configuration/users-import/services/JobService.js, js/pages/configuration/users-import/users-import.html, js/pages/configuration/users-import/users-import.js
fixes https://github.com/OHDSI/WebAPI/issues/1155
=> fixes updating of users after import 

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/estimation/components/cca-executions.js, js/pages/pathways/components/tabs/pathway-executions.js, js/pages/prediction/components/prediction-executions.js
=> Changed format of duration time in executions

js/pages/home/routes.js
=> fixed second login attempt in case of openid auth

js/pages/configuration/users-import/browser.html, js/pages/configuration/users-import/components/job-history.js, js/pages/configuration/users-import/services/JobService.js, js/pages/configuration/users-import/users-import.html, js/pages/configuration/users-import/users-import.js
fixes https://github.com/OHDSI/WebAPI/issues/1155
=> fixes updating of users after import

js/pages/configuration/configuration.html, js/pages/configuration/configuration.js, js/services/AuthAPI.js, js/services/CacheAPI.js
https://github.com/OHDSI/WebAPI/issues/1322
=> added button to clear server cache

js/pages/home/home.html, js/pages/home/home.js, package.json
Updates links and labels to 2.7.5 version
=> updates version to 2.7.5

js/components/cohortbuilder/components/CriteriaGroup.js
=> Add dose era action handler.

js/pages/characterizations/services/conversion/PrevalenceStatConverter.js, js/services/ConceptSet.js, js/utils/CommonUtils.js
Escape value in tooltips.
Introduced new commonUtils function: escapeTooltip.
Updated PrevalenceStatConverter to use commonUtils function.
Fixes #2055.
=> Fix for tooltips in databindings.

js/extensions/bindings/datatableBinding.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/services/conversion/BaseDistributionStatConverter.js, js/pages/characterizations/services/conversion/BaseStatConverter.js, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
Performance updates:
- mark columns XssSafe
- enabled dataTable deferRender and disable autoWidth (both require full table elements to be created slowing down the rendering).
=> Characterization Results Performance Updates

js/components/evidence/components/negative-controls.js, js/pages/concept-sets/components/tabs/explore-evidence.js, js/pages/vocabulary/components/search.js
Small set of changes to address #2091 and #2092.
=> Bug fixes for search token and evidence explorer

js/pages/cohort-definitions/cohort-definition-manager.html
Fixes #2107 by moving it outside of the many containing DIVs so that it can properly set/reset the modal dialog on the page.
=> Move concept set import modal - fixes #2107

js/components/conceptsetbuilder/components/ConceptSetBuilder.js, js/components/conceptsetbuilder/components/ConceptSetBuilderTemplate.html, js/components/conceptsetbuilder/components/IncludedConcepts.js, js/components/conceptsetbuilder/components/MappedConcepts.js, js/pages/incidence-rates/components/iranalysis/components/editor.html, js/pages/incidence-rates/components/iranalysis/components/editor.js, js/pages/incidence-rates/components/iranalysis/components/editor.less, js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js, js/pages/incidence-rates/const.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js
Fixes the following:
Remove RC/DRC columns from concept set picker.  Fixes #1935.
Disable Generate with invalid TAR. Fixes #1008.
=> Incidence Rate UI Updates

js/components/user-bar.html, js/components/user-bar.js, js/services/JobDetailsService.js
=> button for hiding completed jobs was added

js/pages/home/const.js, js/pages/home/home.html, js/pages/home/home.js, js/services/BuildInfoService.js
=> Implements version label should display current version

js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/services/ConceptSet.js, js/utils/CommonUtils.js
=> Fixed concept status after optimization

js/components/faceted-datatable.js, js/pages/concept-sets/components/tabs/included-conceptsets.html
=> Disabled deferRender option in included concepts dataTable

.gitignore, js/pages/home/home.html, js/pages/home/home.js, package.json
Resolves #1910 
Before trying this changes please run:
```
npm install && npm run genversion
```
or make a full build
```
npm run build
```
=> Implements Atlas version display from package.json

js/const.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js, js/pages/pathways/components/tabs/pathway-executions.html, js/pages/pathways/components/tabs/pathway-executions.js, js/pages/pathways/const.js
=> cancel pending jobs

js/components/cohortbuilder/components/CriteriaGroup.js
=> fixed adding dose era criteria 

js/components/cohortbuilder/components/CriteriaGroup.js
=> removed duplicate function

js/components/cohortbuilder/InputTypes/Range.js
=> timezone offset is substracted from date to avoid changing of date

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
=> hiding cohort definitions reports

js/components/welcome.js, js/config/app.js, js/pages/home/routes.js, js/services/AuthAPI.js, js/services/Execution.js, js/services/SourceAPI.js
https://github.com/OHDSI/WebAPI/issues/396
=> added atlas saml authorization support

js/pages/home/routes.js
=> fixed second login attempt in case of openid auth (#2079)

js/pages/estimation/components/cca-executions.js, js/pages/prediction/components/prediction-executions.js
do not show the amount for plp/ple download button
=> do not show amount files for ple/plp download button

js/components/atlas-state.js, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixes showing CC design as actual when cohort changed

js/pages/incidence-rates/ir-manager.html
FIxes https://github.com/OHDSI/Atlas/issues/2133
=> Made IR saving more clear

js/const.js, js/pages/concept-sets/components/tabs/included-conceptsets.js, js/pages/concept-sets/conceptset-manager.js
Fixes https://github.com/OHDSI/Atlas/issues/2190
=> Disabled Included Concepts if lack of permissions

js/pages/concept-sets/components/tabs/conceptset-compare.html
=> adding new concept set is disabled for compare window

js/services/ConceptSet.js
=> fix disappearing of lock icon

js/pages/data-sources/classes/Treemap.js, js/pages/data-sources/components/reports/treemap.html, js/pages/data-sources/data-sources.js, js/services/AuthAPI.js
=> Added check for permissions in data sources tab

js/const.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/components/tabs/included-conceptsets.html, js/pages/concept-sets/components/tabs/included-conceptsets.js
Fixes https://github.com/OHDSI/Atlas/issues/2191
=> Disabled concepts in cohort if lack of permissions

js/pages/cohort-definitions/components/checks/conceptset-warnings.js, js/services/CohortDefinition.js
=> Removed a call to 'check' endpoint during deleting of cohort definition

js/pages/cohort-definitions/cohort-definition-manager.js, js/services/CohortDefinition.js
=> handling cohort not found

js/pages/cohort-definitions/cohort-definition-manager.js
=> added confirmation when concept set expression is not empty

js/pages/estimation/cca-manager.js, js/pages/estimation/components/cca-specification-view-edit.js, js/pages/estimation/components/editors/comparison-editor.html, js/pages/estimation/components/editors/comparison-editor.js, js/pages/pathways/components/manager.js, js/pages/pathways/components/tabs/pathway-design.html, js/pages/pathways/components/tabs/pathway-design.js
Fixed https://github.com/OHDSI/Atlas/issues/2192
=> Added parameter 'isEditPermitted' to PLE & Pathway

js/components/utilities/export.html, js/components/utilities/export.js, js/components/utilities/export.less, js/components/utilities/import.html, js/utils/CommonUtils.js
=> added "copy to clipboard" functionality to export tabs

js/services/CohortDefinition.js
=> Fix loading cohort definition

js/components/cohortdefinitionviewer/components/CriteriaGroup.js, js/components/cohortdefinitionviewer/components/NumericRange.js, js/services/CohortDefinition.js
Fixes PR #2222 by parsing the raw JSON value in the CohortDefinition.expression.
=> Parse raw cohort definition's expression.

js/pages/configuration/configuration.js, js/services/SourceAPI.js
Fixes https://github.com/OHDSI/Atlas/issues/2223
=> Issue 2223 default data-source resets when navigating from and back configuration page

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/concept-sets/components/tabs/conceptset-export.html, js/pages/vocabulary/components/import.js
=> Change order of blocks on concept set export tab

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.less, js/pages/pathways/components/tabs/pathway-design.html, js/pages/pathways/components/tabs/pathway-design.js, js/pages/pathways/components/tabs/pathway-executions.html, js/pages/pathways/components/tabs/pathway-executions.js
Fixes https://github.com/OHDSI/Atlas/issues/2193
=> Disabled Pathway and Feature analyses components if lack of permissions

js/components/terms-and-conditions/terms-and-conditions.js
=> License agreement popup doesn't show up after 30 days (#2210)

js/components/terms-and-conditions/terms-and-conditions.js
=> License agreement popup doesn't show up after 30 days (#2210) for 2.8

js/pages/estimation/components/cca-executions.js, js/pages/prediction/components/prediction-executions.js, js/services/Prediction.js
https://github.com/OHDSI/Atlas/issues/2216
=> fix jobs predictions and estimations

js/pages/estimation/components/cca-executions.js, js/pages/prediction/components/prediction-executions.js
=> PLE/PLP jobs are not shown in notifications modal (#2216) (for 2.8)

js/components/atlas-state.js, js/components/welcome.js, js/services/SourceAPI.js
Fixes https://github.com/OHDSI/Atlas/issues/2223
=> Saved configuration parameters for a session

js/components/atlas-state.js, js/components/welcome.js, js/services/SourceAPI.js
Fixes https://github.com/OHDSI/Atlas/issues/2223
=> [2.8] Saved configuration parameters for a session

js/pages/configuration/configuration.html, js/pages/configuration/configuration.js, js/pages/configuration/routes.js, js/services/AuthAPI.js, js/services/CacheAPI.js, package.json
=> Fixes issue with creating a new source

js/components/name-validation.html, js/components/name-validation.js, js/const.js, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/estimation/components/cca-specification-view-edit.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js, js/utils/CommonUtils.js
Fixes https://github.com/OHDSI/Atlas/issues/2182
=> Added length and symbol check for an analysis name

js/pages/home/home.html, js/pages/home/home.js, package.json
Updates version labels for 2.7.8
=> 2.7.8/version update

js/components/authorship.html, js/components/heading.html, js/components/heading.js, js/components/heading.less, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/components/iranalysis/IRAnalysisDefinition.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js, js/services/ConceptSet.js, js/services/MomentAPI.js, js/utils/CommonUtils.js
=> Added authorship to design header

js/components/cohortbuilder/components/ConditionEra.js, js/components/cohortbuilder/components/ConditionOccurrence.js, js/components/cohortbuilder/components/Death.js, js/components/cohortbuilder/components/DemographicCriteria.js, js/components/cohortbuilder/components/DeviceExposure.js, js/components/cohortbuilder/components/DoseEra.js, js/components/cohortbuilder/components/DrugEra.js, js/components/cohortbuilder/components/DrugExposure.js, js/components/cohortbuilder/components/LocationRegion.js, js/components/cohortbuilder/components/Measurement.js, js/components/cohortbuilder/components/Observation.js, js/components/cohortbuilder/components/ObservationPeriod.js, js/components/cohortbuilder/components/PayerPlanPeriod.js, js/components/cohortbuilder/components/ProcedureOccurrence.js, js/components/cohortbuilder/components/Specimen.js, js/components/cohortbuilder/components/VisitOccurrence.js
=> Fixed descriptions in attributes dropdown list

js/services/ConceptSet.js
Fixes https://github.com/OHDSI/Atlas/issues/2223
=> Added vocab parameter to CS expression request

js/pages/pathways/components/tabs/pathway-executions.html
=> bug fixing

js/assets/ohdsi.util.js, js/components/checks/warnings.js, js/const.js, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-exec-wrapper.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/concept-sets/conceptset-manager.html, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js
=> fixed multiple checks and other errors after merge errors

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/estimation/cca-manager.js, js/pages/pathways/components/browser.js, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.js
=> Page heading doesn't show after reloading (#2265)

js/components/userbar/tabs/user-bar-jobs.html, js/components/userbar/tabs/user-bar-jobs.js, js/components/userbar/user-bar.js
=> Disabled hyperlinks for system jobs

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
=> fixed condition for unavailable execution engine

js/components/cohortbuilder/InputTypes/Range.js
=> Date is converted to string with local timezone

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js, js/services/Permission.js
=> (#2284) PLP/PLE export error

js/pages/concept-sets/components/conceptsets-export.js
only show loader after check selected concept and adding error message of nothing chosen.
fixes #2095
=> Fixes issue #2095

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Fixed FA action buttons state after the cancelation of removal

js/Application.js, js/services/SourceAPI.js
fixes #2261
Now only sources are cached
=> Fixed caching of config api

js/config/app.js, js/pages/incidence-rates/components/iranalysis/components/results.js
=> Issue 2277 fix report button

js/pages/characterizations/components/feature-analyses/const.js
=> Feature analyses "Last Modified" shows only "2+ weeks ago" #2292

js/components/atlas-state.js, js/pages/configuration/configuration.js, js/services/ConceptSet.js, js/services/SourceAPI.js
Backmerge fixes for OHDSI/WebAPI#1595 into 2.8 master
=> Fixes issue with opening conceptSet after relogin (#2267 backmerge)

js/pages/data-sources/classes/Treemap.js, js/pages/data-sources/components/reports/drugEra.js, js/pages/data-sources/components/reports/treemap.html, js/pages/data-sources/components/reports/treemapDrilldown.html, js/pages/data-sources/components/reports/treemapDrilldown.js
=> issue-907: added length of era plot to drug era board

js/pages/vocabulary/components/search.html
=> issue-595: disable search field while loading

js/pages/concept-sets/conceptset-manager.js
=> issue-1932: hid evidence tab for non CEM sources

js/pages/data-sources/components/reports/observation-period.html, js/pages/data-sources/components/reports/observation-period.js, js/pages/data-sources/data-sources.js
=> issue-676 - observation period report

js/components/welcome.js, js/pages/home/routes.js
=> Issue 2286 persist url after login

js/pages/incidence-rates/components/iranalysis/components/editor.html, js/pages/incidence-rates/components/iranalysis/components/editor.js
=> Fixed preserving selected stratify criteria after update

js/components/checks/utils.js, js/components/checks/warnings-badge.html, js/components/checks/warnings-badge.js, js/components/checks/warnings-badge.less, js/components/checks/warnings.html, js/components/checks/warnings.js, js/components/checks/warnings.less, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.js
=> Fixed "Fix it" button at Messages tab

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/services/CohortDefinition.js
=> Dropped legacy cohort features code

js/components/cohortbuilder/InputTypes/Range.js
=> Add parameter for moment.

js/pages/prediction/components/editors/prediction-covariate-settings-editor.html
=> issue-1901: relabel string in prediction covariate settings

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js
fixes #2211 
removes progress field, adds start date and duration fields
=> Heracles progress field is always empty #2211

js/pages/estimation/components/editors/cohort-method-analysis-editor.js
=> createPs is set to true when user specifies inverse probability of treatment weighting (IPTW) for the outcome model

js/pages/concept-sets/concept-manager.js
=> Fixed launching Atlas in bundled mode

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
=> Fixed rendering of cohort reports

js/components/analysisExecution/analysis-execution-list.html, js/components/analysisExecution/analysis-execution-list.js, js/utils/ExecutionUtils.js
=> Fixed "Generating..." button at executions tab

js/pages/configuration/configuration.js, js/services/SourceAPI.js
=> Hides refresh cache button when action is unavailable

js/components/cohortbuilder/CohortDefinition.js, js/pages/cohort-definitions/cohort-definition-manager.js
=> Missed page heading title for New Cohort Definition #2328

js/pages/concept-sets/components/tabs/conceptset-compare.js
fixes https://github.com/OHDSI/webapi/issues/1633
=> fixed concept sets comparison

js/pages/pathways/components/tabs/pathway-results.html, js/pages/pathways/components/tabs/pathway-results.js
=> Show number of people in the path details table instead of only percentages

js/pages/concept-sets/concept-manager.html, js/pages/concept-sets/concept-manager.js
=> Allow Classification concepts in concept hierarchy.

js/pages/estimation/cca-manager.js
fixes https://github.com/OHDSI/WebAPI/issues/1637)
=> fixed error when parsing json with createdBy object

js/pages/cohort-definitions/cohort-definition-manager.js
fixes https://github.com/OHDSI/WebAPI/issues/1622
=> status indicator now shows 'COMPLETED' instead of 'COMPLETE'

js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed  reports for generated cohorts

js/pages/configuration/sources/source-manager.js
=> Fixed dirty flag update after data source saving

build/polyfill.js, js/pages/concept-sets/concept-manager.js
=> Fixed record counts rendering at concept details page if there is a bad data source

js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.html, js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.less
=> prohibits changing of analysis type after save

js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
fixes #2353 
cherry-picked from 31a495d29a7b68210c75110452ea2c99dd317c85
=> Fixing distribution criteria drop-down.

js/pages/concept-sets/conceptset-manager.js
=> New concept set page crashing #2333

js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/cohort-definitions/cohort-definition-manager.js, js/services/CohortDefinition.js
=> Get print-friendly from WebAPI service.

js/components/cohortbuilder/components/ConceptListTemplate.html, js/components/cohortbuilder/components/ConditionEraTemplate.html, js/components/cohortbuilder/components/ConditionOccurrenceTemplate.html, js/components/cohortbuilder/components/CriteriaGroupTemplate.html, js/components/cohortbuilder/components/DeathTemplate.html, js/components/cohortbuilder/components/DemographicCriteriaTemplate.html, js/components/cohortbuilder/components/DeviceExposureTemplate.html, js/components/cohortbuilder/components/DoseEraTemplate.html, js/components/cohortbuilder/components/DrugEraTemplate.html, js/components/cohortbuilder/components/DrugExposureTemplate.html, js/components/cohortbuilder/components/LocationRegionTemplate.html, js/components/cohortbuilder/components/MeasurementTemplate.html, js/components/cohortbuilder/components/ObservationPeriodTemplate.html, js/components/cohortbuilder/components/ObservationTemplate.html, js/components/cohortbuilder/components/PayerPlanPeriodTemplate.html, js/components/cohortbuilder/components/ProcedureOccurrenceTemplate.html, js/components/cohortbuilder/components/SpecimenTemplate.html, js/components/cohortbuilder/components/VisitOccurrenceTemplate.html
=> Add tooltip to remove icon.

js/components/cohortbuilder/InputTypes/Occurrence.js, js/components/cohortbuilder/components/CriteriaGroup.js, js/components/cohortbuilder/components/CriteriaGroupTemplate.html
=> Count criteria now supports different count columns.

js/pages/incidence-rates/ir-manager.js
=> access configuration for incidence rates is now shown

js/pages/estimation/components/editors/outcome-model-args-editor.html, js/pages/estimation/components/editors/outcome-model-args-editor.js
=> auto setting of the regression is disabled

js/components/conceptset/ConceptSetStore.js, js/components/conceptset/included.html, js/components/conceptset/utils.js, js/pages/concept-sets/conceptset-manager.js
This PR modifies how ancestor concepts are loaded to allow drawing of the table to appear sooner.
=> Load ancestor concepts asynchronously.

js/pages/concept-sets/components/concept/components/tabs/concept-hierarchy.js
=> No RC or DRC on Hierarchy tab #2372

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
=> Estimation and Prediction loses Analysis settings during import #2370

js/components/Chart.js, js/components/visualizations/line-chart.js, js/pages/pathways/PathwayAnalysis.js, js/pages/pathways/components/tabs/pathway-design.html, js/pages/pathways/components/tabs/pathway-results.html, js/pages/pathways/components/tabs/pathway-results.js, js/pages/pathways/components/tabs/pathway-results.less, js/pages/pathways/components/tabs/pathway-tableview.html, js/pages/pathways/components/tabs/pathway-tableview.js, js/settings.js, js/utils/ChartUtils.js, package.json
Added export pathway legend function.
Fixed calculation of table reports by removing '-end' markers from pathway results.
New dependency: html2canvas added via NPM.
Renamed ChartUtils function from downloadAsPng to downloadSvgAsPng.
Fixes #2365.
=> Pathway reporting fixes:

js/components/conceptset/conceptset-editor.html, js/components/conceptset/conceptset-editor.js, js/components/conceptset/included-sourcecodes.html
=> Added 'select all' column headers to concept set editor.

js/pages/configuration/users-import/job-view-edit.html, js/pages/configuration/users-import/job-view-edit.js
=> Role mapping ignores provider selector in import jobs #2378

js/pages/cohort-definitions/cohort-definition-manager.js
=> job can be canceled when security is disabled

js/components/cohortbuilder/CriteriaTypes/ConditionOccurrence.js, js/components/cohortbuilder/components/ConditionOccurrence.js, js/components/cohortbuilder/components/ConditionOccurrenceTemplate.html, js/components/conceptpicker/ConceptPicker.js
Add the default domain to the domain options in ConceptPicker.js
Move default domain to top of domain options.
Fixes #404.
=> Added ConditionStatus to UI.

js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.html, js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.js
=> Issue 2389 exclude demographic criteria

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
to prevent situations as in OHDSI/WebAPI#1706
=> do not allow to create copy of FA preset

js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
=> Cannot read property 'type' of null on FE close #2394

js/components/Chart.js, js/components/charts/boxplot.js, js/components/charts/chart.html, js/components/charts/donut.js, js/components/charts/frequencyHistogram.js, js/components/charts/histogram.js, js/components/charts/line.js, js/components/charts/scatterplot.js, js/components/charts/splitBoxplot.js, js/components/charts/treemap.js, js/components/charts/trellisline.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/utils/ChartUtils.js
-Added better implementation to import referenced CSS.
-Fixed constructors to accept params and container element
-Name the charts in cohort characterization
-Unwrap filename paramater, in case the value is an observable.
=> Fix chart export SVG function.

js/pages/home/home.js
fixed webapi version display on home page
=> webapi release version display fix

js/pages/home/home.js
Co-authored-by: anton.abushkevich <anton.abushkevich>
(cherry picked from commit d6046d229eff00721d2d88a14b495b329d98cd8e)
=> webapi release version display fix (#2402)

package.json
Updates version to release 2.8.0
=> Fix version 2.8

js/pages/cohort-definitions/cohort-definition-manager.js
=> Not possible to view a report of cohort definition #2404

js/pages/cohort-definitions/cohort-definition-manager.js
=> #2407 Copy of cohort hang on the PENDING status on the frontend side

js/components/conceptset/ConceptSetStore.js, js/components/conceptset/conceptset-list.js, js/components/conceptset/const.js, js/pages/concept-sets/components/tabs/conceptset-expression.js, js/pages/concept-sets/conceptset-manager.js
=> issue-2410 - fix included concepts tab

js/pages/cohort-definitions/cohort-definition-manager.js
Co-authored-by: anton.abushkevich <anton.abushkevich>
(cherry picked from commit dea279f)
=> #2407 Copy of cohort hang on the PENDING status on the frontend side(#2409)

package.json
=> Updated version of bootstrap-select

js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed graphical view rendering in cohort definitions

js/components/name-validation.html, js/components/name-validation.js, js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/cohort-definitions/cohort-definition-manager.html, js/pages/concept-sets/conceptset-manager.html, js/pages/estimation/cca-manager.html, js/pages/incidence-rates/ir-manager.html, js/pages/pathways/components/manager.html, js/pages/prediction/prediction-manager.html
=> Fixed message for default name error

.gitignore, js/pages/cohort-definitions/cohort-definition-manager.js
=> Fixed copying of cohort definition

js/components/cohort-definition-browser.js, js/components/conceptset/included-sourcecodes.js, js/pages/concept-sets/conceptset-manager.js
=> Fixed stucked loader when trying to create a concept set with an existing name

js/pages/vocabulary/components/search.js
=> Disabled sorting for checkbox column in search results

js/pages/incidence-rates/inputTypes/FieldOffset.js, js/pages/incidence-rates/inputTypes/TimeAtRisk.js
=> Fixed default values for TimeAtRisk

js/pages/data-sources/components/reports/dashboard.js
=> Make person quantity clearer for small data sources #2462

js/pages/concept-sets/components/concept/concept-manager.js
=> It Is not able to add a concept from the concept page #2456

js/components/conceptset/ConceptSetStore.js, js/components/conceptset/conceptset-editor.js, js/components/conceptset/conceptset-list.js, js/components/conceptset/included.js, js/pages/concept-sets/conceptset-manager.js
=> Loader gets stuck after the first attempt to create a concept set #2455

js/pages/cohort-definitions/cohort-definition-manager.js
=> Samples result is not cleared/switched after switching a data source #2464

js/components/evidence/components/negative-controls.js, js/pages/concept-sets/components/tabs/explore-evidence.js
=> Explore Evidence tab in Cohorts doesnt allow to save conceptsets #2454

js/pages/configuration/roles/components/utilities.js, js/pages/configuration/roles/role-details.js
=> Fixed export of role

js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js
=> Fix strata label in prevalence table.

js/pages/characterizations/components/characterizations/characterization-view-edit.html, js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html, js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js, js/pages/estimation/cca-manager.html, js/pages/estimation/cca-manager.js, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.html, js/pages/pathways/components/manager.js, js/pages/prediction/prediction-manager.html, js/pages/prediction/prediction-manager.js
=> Standardize behavior for users with the only public role when opening analyses by direct link #2445

js/pages/concept-sets/conceptset-manager.js
Dispose subscription on destroy().
Call resolve + refresh on component load.
=> Concept Set Manager fixes.

js/pages/incidence-rates/components/iranalysis/components/results.js
=> report can be opened after closed

js/components/evidence/components/negative-controls.js
=> concepts in evidence tab are now shown after selection(#2480)

js/pages/concept-sets/conceptset-manager.html, js/pages/concept-sets/conceptset-manager.js
=> Permission checking for priority daimon has been added

js/components/terms-and-conditions/terms-and-conditions.html, js/components/userbar/user-bar.html
=> Add the ability to disable the localization mode through the configuration #1846

js/pages/data-sources/data-sources.js
=> Set the Observation Period report in a logical order(after the Observation report) #2506

js/pages/pathways/components/manager.html
=> Configure access is not available for pathways #2511

js/components/welcome.html, js/components/welcome.js, js/pages/home/routes.js, js/services/AuthAPI.js
fixes https://github.com/OHDSI/WebAPI/issues/1850
=> error messsage is shown after unsuccessful saml auth

js/components/conceptset/utils.js, js/extensions/bindings/datatableBinding.js
=> Included concepts table is not shown #2518

js/components/terms-and-conditions/terms-and-conditions.js, js/config/terms-and-conditions-content-ru.html, js/config/terms-and-conditions-content-zh.html, js/config/terms-and-conditions.js
=> License agreement should have the same locale as the main application #2516

js/components/utilities/sql.html, js/components/utilities/sql.js, js/components/utilities/sql.less, js/pages/incidence-rates/ir-manager.html, js/pages/incidence-rates/ir-manager.js
=> Export SQL in IR analysis should be disabled if a design is not valid #1864

js/pages/concept-sets/conceptset-manager.js
=> Configure access is unavailable for concept sets #2521

js/components/faceted-datatable.js
=> Facets filters don't work properly #2527

js/components/conceptpicker/ConceptPickerTemplate.html
=> Adding some Demographic criteria is unavailable in Cohort, Characteri… #2529

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html, js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
=> Some of Heracles reports are not shown #2536

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html, js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
(cherry picked from commit e5da9b7b427c4dc8266abde60cae301b6782f529)
=> Some of Heracles reports are not shown #2536 (#2537)

package.json
=> Update version to release 2.9.0 #2534

js/pages/concept-sets/components/concept/components/tabs/concept-hierarchy.html, js/pages/concept-sets/components/concept/components/tabs/concept-related.html
=> Add to New Concept Set button active without checkboxes checked #2501

js/pages/incidence-rates/ir-manager.js
=> Messages tab (IR): loader gets stuck #2514

js/pages/cohort-definitions/cohort-definition-manager.js
=> cohort reports are now available after generation is finished

js/services/ConceptSet.js
fixes https://github.com/OHDSI/WebAPI/issues/1892
=> add error handling for missing concept from non default vocabulary

js/pages/incidence-rates/ir-manager.js
=> Export JSON and SQL in IR analysis should be generated after saving valid analysis design #2522

js/components/conceptset/included-sourcecodes.js, js/components/conceptset/included.js, js/components/conceptset/utils.js, js/const.js, js/extensions/bindings/datatableBinding.js, js/pages/vocabulary/components/search.js
=> Make a checkbox available for selecting all concepts #2543

js/pages/cohort-definitions/cohort-definition-manager.js
fixes https://github.com/OHDSI/WebAPI/issues/1890
=> error messasge is shown when number of patients is out of range

js/components/cohortbuilder/components/ConditionOccurrence.js, js/components/cohortbuilder/const.js
=> name of attribute is now shown

js/components/analysisExecution/analysis-execution-list.js, js/services/Estimation.js, js/services/Prediction.js
fixes https://github.com/OHDSI/WebAPI/issues/1897
=> absent concept set exception is handled now 

js/components/conceptset/included-sourcecodes.js, js/components/conceptset/included.js, js/components/conceptset/utils.js, js/const.js, js/extensions/bindings/datatableBinding.js, js/pages/vocabulary/components/search.js
=> Select all checkbox doesn't work properly with filters #2560

js/components/cohortbuilder/components/WindowInputTemplate.html, js/extensions/bindings/autocompleteBinding.js
=> Inappropriate value in days(Cohort definition) #2563

js/components/cohortbuilder/components/FeasibilityIntersectReport.js
=> Inclusion population visualization shows code as label #2565

js/services/ConceptSet.js
=> javax.ws.rs.ForbiddenException in alert if user does not have vocabulary data source role #2568

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
=> newThresholdValuePct is not updating in characterization #2572

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
=> "Prevalence" count cannot be changed #2583

js/components/cohortbuilder/components/ConditionOccurrenceTemplate.html, js/components/cohortbuilder/components/DeviceExposureTemplate.html, js/components/cohortbuilder/components/DrugExposureTemplate.html, js/components/cohortbuilder/components/MeasurementTemplate.html, js/components/cohortbuilder/components/ObservationTemplate.html, js/components/cohortbuilder/components/ProcedureOccurrenceTemplate.html, js/components/cohortbuilder/components/VisitOccurrenceTemplate.html
=> Incorrect domain "provider specialty" in the attributes of the Cohort #2581

js/components/cohortbuilder/components/CohortExpressionEditor.js
=> Specimen event missed in censoring events #2579

Dockerfile, docker/30-atlas-env-subst.sh
Changes:
- Added an optional config file path in the Docker configuration to put alternative config-local.js
- Bumped Dockerfile dependencies
=> Improve docker config

js/pages/concept-sets/conceptset-manager.js
=> The 'Messages' tab is doubled for a Concept Set #2595

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-design.js
=>  Unavailable to create characterization after adding more then one subgroups analysis #2576

package.json
Merges in changes from rc-2.10.0 and updates the version in package.json
=> Update master branch to 2.11.0-DEV

js/pages/incidence-rates/ir-manager.js
=> Generation results for incidence rates are now visible after switching to another tab

js/components/cohortbuilder/components/CohortExpressionEditor.js
=>  Selecting Censoring event for Payer Plan period fails #2616

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/cohort-definitions/cohort-definition-manager.js, js/pages/concept-sets/conceptset-manager.js, js/pages/incidence-rates/ir-manager.js, js/pages/pathways/components/manager.js
=>  atlas/webapi Versions tab - error when clicking on Preview link when security is disabled WebAPI#1955

js/pages/data-sources/classes/Report.js, js/pages/data-sources/components/reports/person.html, js/pages/data-sources/data-sources.js
=>  Data Source URLs don't work after auth #2625

js/extensions/bindings/datatableBinding.js, js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
=>  Sorting in Characterization report #2663 

js/components/conceptset/import.html, js/components/conceptset/import.js, js/components/conceptset/import.less
=> Import concept set from repo - choose from overwrite and append #2654

js/components/conceptset/import/sourcecodes.html, js/components/conceptset/import/sourcecodes.js, js/components/conceptset/import/sourcecodes.less
=> Issue 2653 targeted concept import

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
This PR changes the init behavior of the `characterization-results` component by responding to changes in the `generationId` param by loading the design, and updates to the filtering will refresh the results data.  Loading the new design will also reset the filter options, which will trigger a refresh of the data.   
Before this change, it appeared the design and dataload was being called twice. This way is a bit easier to follow and I think works more efficiently.
=> Fixes #2651.

js/config/app.js, js/pages/vocabulary/components/search.html, js/pages/vocabulary/components/search.js, js/services/CDMResultsAPI.js, js/services/Vocabulary.js
=> Issue 1981 add person count

js/pages/reusables/components/tabs/reusable-design.js
=>  Cannot insert reusable with assigned concept sets into another reusable #2668

js/utils/DatatableUtils.js
=>  Use username (if exists) in table filter instead of login #2670 

js/pages/vocabulary/components/search.js, js/services/AuthAPI.js
=> List only user-accessible sources in search results #2672 

js/pages/reusables/components/manager.html
=> No "delete" icon in reusables #2674 

js/pages/reusables/components/tabs/reusable-design.js
=>  Several equal parameters in Reusables editor #2676 

js/pages/reusables/components/tabs/reusable-design.html
=>  Cannot change description of a copy of a reusable which was created by another user #2678

js/pages/characterizations/components/characterizations/characterization-view-edit.js
=>  Unify deletion alert messages #2680 

js/pages/reusables/components/tabs/reusable-design.html, js/pages/reusables/components/tabs/reusable-design.less
=>  Add warning message to reusables about using types #2684

js/pages/reusables/components/tabs/reusable-design.js
=>  Reusables: changes in Concept Sets tab do not reflect in the design dropdowns #2689

js/pages/cohort-definitions/cohort-definition-manager.html
=>  Double loading indicator when opening Cohort #2691 

js/pages/characterizations/components/characterizations/characterization-view-edit.js, js/pages/reusables/components/tabs/reusable-design.html, js/pages/reusables/components/tabs/reusable-design.js, js/pages/reusables/components/tabs/reusable-design.less, package.json
Post v2.11.0 release - merging code into master
=> Merge rc-2.11.0

js/pages/concept-sets/components/tabs/conceptset-compare.js
=>  Concept Sets comparison allows to choose from sources unavailable to current user #2705

js/pages/estimation/cca-manager.js, js/pages/prediction/prediction-manager.js
=>  User with human readable name cannot grant access to their PLP and PLE #2714

js/pages/data-sources/classes/Report.js
=>  Changing Data Source does not update the reports on Atlas 2.11.1 #2741

js/components/from-reusables-modal/from-reusables-modal.html
=>  Insert from Reusable: change “Any Condition” to “Any Concept Set” #2747

js/pages/prediction/components/editors/prediction-covariate-settings-editor.html
Fixes #2645
syntax error - removed extra quote
=> Patient level prediction covariate settings include/exclude concepts popup broken. #2645

js/components/conceptpicker/ConceptPicker.js
=> Update ConceptPicker to VocabularyService API.

js/components/tags/modal/tags-modal.js
=>  Tags table rendering error #2782

js/pages/incidence-rates/ir-manager.js
=>  403 error when removing IR generation result not displaying properly #2783

js/components/tags/modal/tags-modal.js, js/pages/configuration/configuration.html, js/pages/configuration/configuration.js, js/pages/configuration/routes.js, js/pages/configuration/tag-management/tag-management.html, js/pages/configuration/tag-management/tag-management.js, js/pages/configuration/tag-management/tag-management.less, js/services/AuthAPI.js, js/services/Tags.js
=>  Add tagging management through UI #2773 

index.html, js/Application.js, js/components/feedback.html, js/components/feedback.js, js/components/welcome.html, js/components/welcome.js, js/config/app.js, js/styles/atlas.css
Resolves #2795 
Added overridable config fields:
`feedbackContacts` - text before email link
`feedbackCustomHtmlTemplate` - user-defined text block on the feedback page
`showCompanyInfo` - turns on-off lower-left block with logo
`companyInfoCustomHtmlTemplate` - override default lower-left block
Added placeholders for login and password text fields:
`authProviders[n].loginPlaceholder`
`authProviders[n].passwordPlaceholder`
=> Add custom logo enhance url support

js/components/charts/horizontalBoxplot.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.html, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js, js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less, js/pages/characterizations/components/characterizations/characterization-view-edit/utils.js, package.json
=> Add cohorts box plots regardless of selected cohorts

js/components/charts/venn.js, js/pages/concept-sets/components/tabs/conceptset-compare.html, js/styles/atlas.css
=> i18n for venn diagram

js/components/utilities/sql/sqlExportPanel.html, js/components/utilities/sql/sqlExportPanel.js, js/components/utilities/sql/sqlExportPanel.less, js/components/utilities/sql/sqlExportPanelConfig.js, js/settings.js, js/utils/HighLightUtils.js
Resolves #2775 
- added SQL syntax highlight
- added variables (parameters) replacement (switch between parameters names and parameters values)
=> Add highlights sql output

js/extensions/bindings/expressionCartoonBinding.js
=> Cohort graphical view - fixed position of tooltip

package.json
=> 2.12.1 release - version update

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.less, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js, js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.less, js/pages/characterizations/services/conversion/BaseStatConverter.js
=> Add proportional shading to characterization data tables

js/components/cohortbuilder/CriteriaTypes/VisitDetail.js
=>  npm run build fails on master branch #2786

js/components/utilities/sql/sqlExportPanel.html, js/components/utilities/sql/sqlExportPanel.js
=> SQL Export template error on new Cohort #2825

js/pages/concept-sets/components/concept/components/tabs/concept-drilldown-report.html, js/pages/concept-sets/components/concept/components/tabs/concept-drilldown-report.js
there's no need in getting record counts for this tab
fixes #2819
=> loading record counts was removed from concept drilldown tab

js/pages/pathways/components/tabs/pathway-tableview.html, js/pages/pathways/components/tabs/pathway-tableview.js
=> Check for empty data condition.

js/components/conceptAddBox/concept-add-box.js
=>  Concept added to a concept set has no Exclude/Descendants/Mapped flag #2838

js/components/cohortbuilder/components/VisitDetail.js, js/components/cohortbuilder/components/VisitOccurrence.js
=>  "Place of service distance" criteria for a Visit Occurrence criteria is misfunctional #2814

js/Application.js, js/main.js
=> Move databindings loading to application bootstrap.

js/components/cohortbuilder/components/ConditionOccurrence.js, js/components/cohortbuilder/components/Death.js, js/components/cohortbuilder/components/DeviceExposure.js, js/components/cohortbuilder/components/DoseEra.js, js/components/cohortbuilder/components/DrugEra.js, js/components/cohortbuilder/components/DrugExposure.js, js/components/cohortbuilder/components/LocationRegion.js, js/components/cohortbuilder/components/Measurement.js, js/components/cohortbuilder/components/Observation.js, js/components/cohortbuilder/components/ProcedureOccurrence.js, js/components/cohortbuilder/components/Specimen.js, js/components/cohortbuilder/components/VisitDetail.js, js/components/cohortbuilder/components/VisitOccurrence.js, js/extensions/bindings/i18nBinding.js
=> Make indexMessage respond to observable changes.

js/components/cohort-comparison-multi-r-code.js, js/components/utilities/sql/sqlExportPanel.js, js/settings.js, js/utils/HighLightUtils.js
=> Ensure prism loads in correct order.

js/pages/incidence-rates/components/iranalysis/components/results.html, js/pages/incidence-rates/components/iranalysis/components/results.js
Aims to address #2904 by updating the buttons used to generate incidence rate analysis. Additionally, I've added the ability to cancel IR generation since this was not present upon my review.
=> IR generation button fixes

js/Application.js
Addresses https://github.com/OHDSI/Atlas/issues/3001
Adds new listeners that detect user activity and refresh auth token if user is actively using the Atlas UI.
=> Refresh auth token if user is actively using the Atlas UI

docker/nginx-default.conf
Addresses https://github.com/OHDSI/Atlas/issues/2999
=> Add better caching instruction to headers
