index.html
js/main.js

We were having issues running Atlas on HTTPS. This works for me local (http) or on our server (https).
Thanks.

fix resource URLs to work with http or https

---

js/jnj.chart.js

Evaluation of `Y_PREVALENCE_1000PP` when `Y_PREVALENCE_1000PP=0` will cause `yPrevalence1000Pp` to be evaluated (a property which doesn't exist in later versions of Achilles output) and yields undefined and thus results in NaN values in graphs. Using `hasOwnProperty` seems to produce the desired behavior in the contexts I have described in the issue.

Explicit check of d.Y_PREVALENCE_1000PP (fixes #137)

---

.gitignore
.jshintrc
index.html
js/app.js
js/components/data-sources.html
js/jnj.chart.js
js/ohdsi.util.js
js/styles/achilles.css
js/styles/atlas.css

It turns out the issues we were seeing with the legacy achilles (data sources) charts was due to some undeclared variables throwing errors once "use strict" was applied on the charting module.  I've put a few things into this branch that I wanted to open up for comment before pushing to master.
I added .jshintrc which is a preference file for JSHint.  JSHint is a javascript code analysis tool.  The .jshintrc file will allow us to set conventions for our code that we can then test for compliance.  The current .jshintrc is by no means "our accepted standards" just a template I found that seemed well formed.  I then made changes to bring the charting module file down from a few hundred JSHint problems to 39.  I stopped there as the problems were getting harder to resolve and I wasn't sure if …

trying to use linters and fixing achilles

---

js/app.js
js/components/cohort-comparison-manager.js
js/components/conceptset-manager.js
js/modules/WebAPIProvider/CohortDefinitionAPI.js
js/modules/WebAPIProvider/ConceptSetAPI.js
js/modules/WebAPIProvider/IRAnalysisAPI.js

This PR normalizes the HTTP verbs in WebAPI such that POST = create, and PUT = update.
This is necessary to support backwards compatibility int he upcoming Shiro branch.

HTTP verb normalization.

---

js/app.js

Adding in the ability to see parent/child relationships for ATC 4th and 5th concepts. Also extended the metatrix object to support an optional "vocabulary" property which allows you to specify an array of vocabularies to consider along with the concept relationship and range. This was added to provide the ability to show parent ETC and ATC ancestor concepts in the hierarchy view for a selected RxNorm Ingredient concept. The dependent function hasRelationship was modified to support this optional property.
@fdefalco - I'd like your feedback on the approach since your familiar with this functionality
@pbr6cornell  - Please provide your feedback around the hierarchy configuration I've specified. For RxNorm Ingredient concepts, we originally considered all parent concepts that had a …

Fixes #215 and adds further granularity for parent/child by vocabulary

---

js/components/cohort-definition-manager.html
js/modules/databindings/htmlValueBinding.js

Use contenteditable databind instead of htmlValue.  Chrome 57 breaks the htmlValue binding.

Fixes #384.

---

js/components/atlas.cohort-editor.html
js/components/atlas.cohort-editor.js
js/components/cohort-definition-manager.html
js/components/conceptset-browser.html
js/components/ir-manager.html
js/components/ir-manager.js
js/main.js
js/modules/circe/components/CohortConceptSetBrowser.js
js/modules/circe/components/CohortConceptSetBrowserTemplate.html
js/modules/cohortbuilder/bindings/dropupBinding.js
js/modules/cohortbuilder/components.js
js/modules/cohortbuilder/components/CohortExpressionEditor.js
js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html
js/modules/cohortbuilder/components/ConceptSetQuickview.js
js/modules/cohortbuilder/components/ConceptSetQuickviewTemplate.html
js/modules/cohortbuilder/components/ConceptSetSelector.js
js/modules/cohortbuilder/components/ConceptSetSelectorTemplate.html
js/modules/cohortbuilder/css/builder.css
js/modules/databindings/eventListenerBinding.js
js/styles/atlas.css

This is the implementation of the feature request from @jhardin29 to implement conceptset quickview on the cohort builder.  Changes are as follows:
Cohort Editor now provides the ability to preview a concept set and make minor modifications (exclude, descendants, mapped).
Modified conceptset picker so that dropdowns can be bound to events.
Updated sortable ko binding to version 1.0.1.
Modified event databinding to return binding context with the data item.
Modified concept set browser to only show repository concept sets.
Closes OHDSI/WebAPI#228.

Cohort Editor: Concept Set Preview

---

js/app.js
js/components/concept-manager.js
js/components/faceted-datatable.js
js/config.js
js/main.js

Provides support for passing in arrays as a facet filter. This was necessary for a bug found by @ericaVoss for the 'Related Concept' tab for a concept. The root cause is that the facets for 'Relationship' and 'Distance' were based on an array of nested values returned from the REST endpoint. This change provide a mechanism to specify if a given facet dimension is an array per https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_with_arrays. Furthermore, it changes the specification for the facet so that each dimension can be interrogated for the proper value.
Also bumps the crossfilter reference from 1.4.0 to 1.4.1 since it contained a fix related to array dimensions utilized here.

Handle arrays in faceted data table.

---

.gitignore
js/config.js
js/main.js
js/plugins/optional.js

attempting to provide a way to allow local configuration without editing of config.js, which we would like to remain out of the .gitignore as new features / configurations are introduced.
config-local.js would be added to .gitignoreafter initial commit.

allowing for local configuration

---

js/app.js
js/components/report-manager.html
js/components/report-manager.js

@anthonysena Anthony, please review. Those are for "care site" based entropy for [issue 223](https://github.com/OHDSI/WebAPI/issues/223) and [issue 217](https://github.com/OHDSI/WebAPI/issues/217)

care site entropy

---

js/modules/cohortbuilder/CohortExpression.js
js/modules/cohortbuilder/components/CohortExpressionEditor.js
js/modules/cohortbuilder/components/CohortExpressionEditorTemplate.html
js/modules/cohortbuilder/options.js
js/modules/cohortdefinitionviewer/components/CohortExpressionViewerTemplate.html

UI functionality only. Additional work is needed to make changes to cohort-constructor logic based on user input.
UI for era-fy 
https://github.com/OHDSI/WebAPI/pull/234
https://github.com/OHDSI/WebAPI/issues/217
https://github.com/OHDSI/Atlas/issues/414
https://github.com/OHDSI/Atlas/issues/375
https://github.com/OHDSI/Atlas/issues/407
@chrisknoll

UI functionality to choose collapse strategy exit criteria

---

js/modules/cohortbuilder/AdditionalCriteria.js
js/modules/cohortbuilder/InputTypes/RestrictVisit.js
js/modules/cohortbuilder/components/CriteriaGroup.js
js/modules/cohortbuilder/components/CriteriaGroupTemplate.html
js/modules/cohortdefinitionviewer/components/CriteriaGroupTemplate.html

This PR adds new functionality in Atlas. 
UX to circe-be functionality to restrict qualified-events to the same visit_occurrence_id. _era tables, death, observation period, specimen are excluded from this functionality.
https://github.com/OHDSI/Atlas/issues/454
https://github.com/OHDSI/WebAPI/issues/217
https://github.com/OHDSI/circe-be/pull/7
https://github.com/OHDSI/circe-be/pull/8
@chrisknoll

New front end functionality to restrict to records with the same visit_occurrence_id

---

js/components/data-sources.html
js/components/data-sources.js
js/styles/atlas.css

This PR sets the dimensions for the various plots in the datasources so that the font size and scaling looks consistent.
@t-abdul-basser , @mark-velez : while fixing this up, I noticed there were plots missing from the Measurement reports (recordsByType, etc).  I was going to fix that in this PR, but as I was going through it, I think there's a bug in the WebAPI query for the measurement data, as the recordsByType collection was pulling down more data than expected and the donut chart was not working. So, I left place holders for the plots in this PR, and was hoping you guys would take a look. I will open a separate issue for the Measurement reports.

Updated plot dimensions for datasources.

---

js/modules/cohortbuilder/components/ConceptSetSelectorTemplate.html

This PR addresses an issue that was identified when looking at cohort definitions with large numbers of concept sets.  A UI component was being rendered needlessly which was causing the UI to hang.

Fixed redundant quickview component causing a slowdown in page.

---

js/app.js
js/components/cohort-definitions/cohort-definition-manager.js
js/components/conceptset/conceptset-manager.js
js/components/ir-manager.js
js/components/plp-manager.js
js/components/role-details.js
js/components/user-bar.html
js/components/user-bar.js
js/components/welcome.html
js/components/welcome.js
js/main.js
js/modules/WebAPIProvider/AuthAPI.js

- Introduces centralized token refresh (on navigation to a new page)
- When the token is expired, displays login form with notification to let the user to re-login and continue working w/o loss of progress.
Closes https://github.com/OHDSI/Atlas/issues/677. Instead of https://github.com/OHDSI/Atlas/pull/678
(We cannot refresh token on ajax's "beforeSend", because some of ajaxs are called by setInterval and that would break session timeout functionality).
@chrisknoll , @johnSamilin

Centralized token refresh

---

js/components/home.html
js/main.js

These fixes from 2.4.2 include updating the home page version, and updating the reference to AtlasCharts.

Fixes from v2.4.2

---

js/components/plp-r-code.html

Some of the ML model parameter names don't match the actual parameter names in current versions of PatientLevelPrediction.  For instance, setRandomForest specifies 'max_depth', but the actual parameter name is 'maxDepth'.

Fixed parameters for various ML models

---

js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/cohort-definitions/components/reporting/cost-utilization/base-report.js
js/pages/cohort-definitions/components/reporting/cost-utilization/persons-exposure.html
js/pages/cohort-definitions/components/reporting/cost-utilization/visit-util.html
js/settings.js

Fixed bootstrap-select styling
Fixed Cost & Util analyses selection modal
Do not display detailed data tables / charts when only summary is calculated for Cost & Util

Cost & Util fixes & improvements

---

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html
js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
js/services/CohortReporting.js

Fixed column labels for cohort report tables (procedure, drug, etc) due to concept_hierarchy changes.
Made Quick Analysis use visualization packs to reduce error of specifying individual analysis IDs.

Cohort Reporting Adjustments

---

js/components/terms-and-conditions/terms-and-conditions.js
js/config/app.js

Enables the ability to override if the terms & condition modal is shown. By default, it will be set to `true` in the base configuration file.

Fixes #932

---

js/pages/configuration/sources/source-manager.js

When adding a source for MS SQL on the Configuration page, the SOURCE_DIALECT column of the source table is loaded into sqlserver, which prevents the connection from being made properly. (The correct DIALECT is sql server)

Fix source database connection check error in Microsoft SQL Server

---

js/components/evidence/components/negative-controls.js
js/services/SourceAPI.js

Aims to close #1064; I had re-used the `hasResults` flag on the CEM source which was causing problems with the record count display.
Also revised the warning message when exploring evidence per OHDSI/WebAPI#397

Create separate source flag for sources configured with CEMResults

---

js/pages/concept-sets/concept-manager.js
js/pages/concept-sets/conceptset-manager.html

Please test this with OHDSI/WebAPI#716. Aims to correct errors observed when testing that PR whereby concepts that have no records in a CDM, the concept record count tab fails to load. Furthermore, when navigating away from a concept page to another section of the application (`onRouterParamsChanged`), an exception was thrown so I added in a check to determine if a valid conceptId is defined.

Concept record count fixes and closing concept set fix

---

js/Application.js
js/services/AuthAPI.js

The PR fixes Atlas behavior, when it is not showing error when app is in secured mode, sources were cached and WebAPI is down

Fail app bootstrapping process if user info is unavailable

---

js/Model.js
js/components/circe/components/CohortConceptSetBrowser.js
js/pages/concept-sets/components/tabs/conceptset-compare.js
js/pages/concept-sets/concept-manager.html
js/pages/concept-sets/conceptset-manager.html
js/pages/concept-sets/conceptset-manager.js
js/pages/concept-sets/routes.js
js/services/Vocabulary.js

This PR aims to address a number of concept set/vocabulary bugs:
#282 - Concept Set Comparison Caching Definition
#568 - Multiple resolveConceptSetExpressions result in race condition
#620 - Optimizing a null conceptset causes issue
#702 - Trashing an unsaved concept set
#728 - Distance in hierarchy does not match value from concept_ancestor
#1133 - Clicking the "save new concept set from selection below" button in concept set compare tab creates odd concept set
#1228 - Import concept set in cohort definition throws error
#1229 - Optimize concept set fails
The commits in this PR are organized by the issues above. Please let me know if you have any questions or concerns with these fixes.

Concept set fixes

---

js/pages/pathways/components/tabs/pathway-results.less

fixes https://github.com/OHDSI/Atlas/issues/1219

Fixed flex container and margins to display Pathways results on small display properly

---

js/components/generation/select-sources-btn.html
js/components/generation/select-sources-btn.js
js/components/generation/select-sources-popup.html
js/components/generation/select-sources-popup.js
js/pages/incidence-rates/components/iranalysis/components/results.html
js/pages/incidence-rates/components/iranalysis/components/results.js

When working through the changes for #1292, it was difficult to follow how the set of source choices was being transformed between the IR UI -> generate button -> select-source-popup -> IR execution callback.  In the process of several transforms, the starting point of a set of sources gets resolved to a set of keys.  While tracing through it, I was imaging some questions that might be reaised by someone who is not familar with the code:
How does the consumer know that the set of sources I pass in comes back as an array of strings that represent keys?
If i want to reuse some of this, or generalize it, does it require that an object being chosen have a 'key' property?
To simplify things, this PR changes it so that when you pass the set of sources as your 'set of options/choices', the call …

Make source selection always reference the objects to select instead of returning keys.

---

js/pages/cohort-definitions/cohort-definition-manager.js

The parameter passed to `appendConcepts` is the response from the server, not the payload:
So I've changed the function to expect the response and not the payload.

Fixes #1372 - Concept Import for Cohort Concept Set

---

build/polyfill.js

fixes https://github.com/OHDSI/Atlas/issues/1418
In non-bundled mode `less.js` adds polyfill for non-standardized `Promise.done`:
During bundling this thing seems to be cut off by requirejs optimizer. Even though the `Promise.done` is not a standard thing and as for me should be avoided going further, right before the release of 2.7.0 I'm not treating migration of `done` -> `then` as a good idea. Therefore, I've brought that exact piece of code from `less.js` into `polyfill.js` which is imported by bundler.

Added Promise.done polyfill

---

js/components/conceptsetmodal/conceptSetSaveModal.js

Fixes #1425. The new code now checks to see if the concept set modal is shown and when that happens, it calls `self.conceptSetName.valueHasMutated()` which then triggers the checks to make sure the concept name is unique.

Prevents concept set duplication 

---

js/components/conceptpicker/conceptpicker.less
js/components/conceptsetbuilder/components/IncludedConcepts.js
js/components/conceptsetbuilder/components/MappedConcepts.js
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/concept-sets/components/tabs/conceptset-compare.js
js/pages/concept-sets/components/tabs/included-conceptsets.js
js/pages/concept-sets/concept-manager.js
js/pages/vocabulary/components/search.js
js/styles/atlas.css
js/utils/CommonUtils.js

Updates the commonUtils to share a common way to determine the `standard_concept` designation of a concept and to return a css class defined in atlas.css. 
Fixes #1527

Fix concept link display

---

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html
js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js

fixes #1363 
button becomes disabled when no cohorts found
hint was changed

Prevent execution of executing CC with zero cohorts(#1363)

---

js/Model.js
js/components/cohort-definition-browser.js
js/components/faceted-datatable.js
js/extensions/bindings/datatableBinding.js
js/extensions/bindings/profileChart.js
js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/cohort-definitions/components/checks/conceptset-warnings.html
js/pages/concept-sets/components/tabs/conceptset-expression.html

This is ready for review.
Following changes:
- Allow table to be marked 'xssSafe' to prevent unnecessary string parsing and formatting.
- Modifications to datatabinding to not trigger dependency tracking during redraws.
- Added cleanup (via DataTable.destroy()) when binding's element is disposed.
- Had to disable saveState/loadState callbacks from Warnings compnent: this led to a conflict.
- Found some cases where data-tables `render` options were returning the same formatted value for all types of render (type, sort, display, filter) which led to strange sorting results with hyperlinks.  This could also be applied to fix sorting on date columns that are currently using moment-parse-date routines that are extremely expensive. (However, not addressed in this PR).
Partially addresses #1581. …

Datatables performance/clean-up improvements

---

js/pages/vocabulary/components/search.js

Fixes #250 through proper encoding and a work-around for the "/". The way search currently work is by redirecting to a new URL:
`atlas/#/search/<search term>`
If your `<search term>` contains a "/" it messes up the route handling since it can't determine if the "/" is part of the URL or instead is part of the search term. I've added a work-around that eliminates the "/" from the search itself and replaces it with a space. This is a hack for sure but is a quick fix and takes advantage of the current search which will insert a wildcard for spaces.

Vocabulary search - handle special characters

---

js/Model.js
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/vocabulary/components/import.js

Per #1532, this PR updates the way in which we import concept identifiers so that we're not pushing each individual item into the `sharedState.selectedConcepts` observableArray. Instead, we add the items to a traditional array and once complete, set `sharedState.selectedConcepts` to take that array as its value.
This PR also addresses #1525 so that you can append concept identifiers to an open repository concept set without having to do additional work. This changes makes the repository and cohort concept set experience identical - you can append concepts through the import functionality.

Concept set import fixes

---

js/Application.js

Per #1526, when using the "select all" on a faceted data table, the concepts are properly selected but the table's state is reset wiping out any user-defined facet filters, options, etc. To accomplish this, I've removed the call to `ko.contextFor(this).$component.reference.valueHasMutated()` since this call causes the entire data table to be re-drawn which is inefficient. 
Instead, I've reused the `table` variable that is declared earlier in the function to obtain the concepts that exist in the data table with all of the filters/options applied. The loop below:
```
for (var i = 0; i < table.rows()[0].length; i++) {
table.cell(i,0).data('<i class="fa fa-shopping-cart"></i>');
}
```
What this is doing is obtaining the length of the filtered data: `table.rows()[0].length` and then applies …

Select all concepts fix

---

js/pages/estimation/components/cca-specification-view-edit.js
js/pages/prediction/components/prediction-specification-view-edit.js

For Estimation & Prediction, call the `valueHasMutated` on the referenced observableArray to force the summary table to reload once the user is done editing the values.

Update plp/ple settings display - fixes #1710

---

js/services/Vocabulary.js

Requires changes from OHDSI/WebAPI#1039 and assumes you have run the Achilles analyses added as part of OHDSI/Achilles#393

Get record counts for non-standard concepts

---

js/pages/data-sources/classes/Treemap.js
js/pages/data-sources/data-sources.js

Moved `dispose()` out of constructor and added call to parent class `dispose()` to ensure proper subscription cleanup that was making extraneous calls to WebAPI after viewing different reports and then switching sources.
Added an additional condition to `js/pages/data-sources/data-sources.js` to prevent multiple calls to the `updateLocation()` which was also contributing to extra WebAPI traffic.

Treemap component disposal - Fixes #1715

---

js/components/cohortbuilder/components/CriteriaGroupTemplate.html

Moved the checkbox out of the 'restrictVo' div, which was causing it to be hidden for criteria that was not associated with a Visit Occurrence (such as condition era).

Show 'allow events outside observation period' option in all cases.

---

js/pages/concept-sets/conceptset-manager.js

Uses the model's clearConceptSet() method after deletion to remove stale references to fix #1750.

Delete concept set - fixes #1750 - v2.7.2-rc

---

js/pages/concept-sets/conceptset-manager.js

Uses the model's clearConceptSet() method after deletion to remove stale references to fix #1750.
fixes #1750

Delete concept set - fixes #1750 - master

---

js/pages/concept-sets/conceptset-manager.js

Call `sharedState.clearSelectedConcepts()` when overwriting the current concept set through the optimize utility. Fixes #1751.

Concept set state fix after optimize - fixes #1751 - v2.7.2-rc

---

js/pages/concept-sets/conceptset-manager.js

Call `sharedState.clearSelectedConcepts()` when overwriting the current concept set through the optimize utility. Fixes #1751.

Concept set state fix after optimize - fixes #1751 - master

---

js/components/cohort-definition-browser.html
js/components/cohort-definition-browser.js
js/components/faceted-datatable.js
js/styles/atlas.css

2 Issues addressed:
1. Sorting a large table on date resulted in excessive date parsing and comparison.  The solution adds a new 'timestamp' column that is pre-calculated as an integer so sorting can be performed without parsing.
2. Added css classes to fix the created/updated and author columns.  This uses a fixed column width.  The reason this felt necessary was due to the following behavior:
Without fixed columns:
With fixed Columns:
Fixes #1571.

Added sort column to cohort definition list to improve performance. 

---

js/pages/cohort-definitions/cohort-definition-manager.js

Fixes #1753 by calling the model's `loadCohortConceptSet()` function. Also applied a similar fix on this PR as was done in #1651 to help the performance when loading in larger concept sets.

Cohort included concept display - fixes #1753 - master

---

js/components/cohort-definition-browser.html
js/components/cohort-definition-browser.js
js/components/faceted-datatable.js
js/styles/atlas.css

2 Issues addressed:
1. Sorting a large table on date resulted in excessive date parsing and comparison.  The solution adds a new 'timestamp' column that is pre-calculated as an integer so sorting can be performed without parsing.
2. Added css classes to fix the created/updated and author columns.  This uses a fixed column width.  The reason this felt necessary was due to the following behavior:
Without fixed columns:
With fixed Columns:
Fixes #1571.

Issue 1571 [v2.7.2]

---

js/pages/data-sources/classes/Treemap.js

Ensures that only unique entries are shown in the table display for the data sources "treemap" reports. For example, before this PR, here's how the table display looks like for the drug exposure report for concept_id == 19080128
and after:
This is using the approach described in issue https://github.com/OHDSI/Atlas/issues/913#issuecomment-496967558

Remove duplication in data source table - #913

---

package.json

Without this update & npm build, the scatter plot fixes done for #1758 are not available.

Update atlascharts reference to v1.7.3 in package.json 

---

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js

Hides the "Create new concept set" button from the characterization results display per #1834.

Hide create cs button - fixes #1834 - master

---

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js

Hides the "Create new concept set" button from the characterization results display per #1834.

Hide create cs button - fixes #1834

---

package.json

Fixes #1830. Actual issue was in `bootstrap-select`, therefore, opening this PR instead of https://github.com/OHDSI/Atlas/pull/1832

Specify concrete version of bootstrap-select since upcoming versions bring issues with flex markup

---

package.json

Specify concrete version of bootstrap-select since upcoming versions bring issues with flex markup (2.7.2)

---

js/pages/cohort-definitions/cohort-definition-manager.css
js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js

Prevent a user from exporting all concept sets from a cohort definition until there is at least 1 concept set in the definition and the definition has been saved to the server. Also added a warning message to indicate why the button is disabled.
fixes #1853

Add checks for concept set export - fixes #1853

---

js/components/evidence/options.js
js/components/evidence/utils.js

Updates the negative control table options to use the `render` property where applicable. Updated to centralize formatters to a single function call. Fixes #1888

Fix candidate negative control display

---

js/pages/incidence-rates/ir-manager.js

Could use some feedback from @chrisknoll @pavgra on this.
Here is the issue: when the `js/pages/incidence-rates/ir-manager.js` component is loaded, the `init()` is called asynchronously. Before the changes in this PR, this would call the WebAPI's sources endpoint to retrieve the sources and find those that are configured with both a CDM & Results daimon. With the changes I've made in this PR, this information will be retrieved from the `sharedState` thus preventing a round-trip to the server. 
There is still a potential race condition here: in the case of #1883, the IR analysis is already loaded such that when the `onRouterParamsChanged` function is called, it will automatically start polling for updates to the source. Within the `pollForInfo` function, it requires that the sources with a …

Fix polling delay in IR - fixes #1883

---

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html

This pull request requires the corresponding changes in https://github.com/OHDSI/WebAPI/pull/1195. Revising the WebAPI queries corrects the problem noted in issue #1872.
During the investigation of #1872, I noted that the display in the cohort reporting for Drug reports is incorrect. Per the [concept_hierarchy construction](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/ddl/results/init_concept_hierarchy.sql#L171), the display should be **ATC 4th**.

Update ATC heading display - fixes #1872

---

js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js
js/services/CohortReporting.js

This is a fix for OHDSI/WebAPI#933. It should be tested in conjunction with https://github.com/OHDSI/WebAPI/pull/1194.
I've added the additional Heracles analysis IDs that are required to display all of the results for the condition & drug era reports run during the "Quick Analysis" for cohort reporting in `js/services/CohortReporting.js`.  Additionally I fixed some typos that were preventing proper rendering of the cohort & drug era reports in `js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.js`.

Fix quick analysis IDs; fix typos in report mgr

---

js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
js/pages/characterizations/components/characterizations/characterization-view-edit/explore-prevalence.js
js/pages/characterizations/components/feature-analyses/const.js
js/pages/characterizations/const.js
js/pages/characterizations/services/conversion/PrevalenceStat.js
js/pages/characterizations/services/conversion/PrevalenceStatConverter.js
js/pages/characterizations/utils.js

Fixes #1926 
As discussed with @pavgra CC covariate name will stay original if faType is CUSTOM_FE/CRITERIA.

Fixed render of cc covariate name

---

js/pages/cohort-definitions/cohort-definition-manager.html

Per #1933, hiding the message tab in the cohort definition editor as it is incorrectly displaying messages that if you attempt to fix using the "Fix It" link may corrupt the definition.

Hide the cohort definition messages tab #1933

---

js/Model.js
js/pages/concept-sets/conceptset-manager.js
js/services/ConceptSet.js

Fixes issue #1930 by ensuring that the newly optimized concepts are added to the shared state collection:
`sharedState.selectedConceptsIndex[item.concept.CONCEPT_ID] = 1;`
Also done here:
- Corrected the spelling of enhanceConceptSet in `js/services/ConceptSet.js` and carried through the proper function name in the code base where applicable
- Used enhanceConceptSet in favor of the code that was duplicated in the function `overwriteConceptSet` (js/pages/concept-sets/conceptset-manager.js)

Optimize concept set fix (#1930)

---

js/components/atlas-state.js
js/pages/configuration/configuration.html
js/pages/configuration/configuration.js
js/pages/configuration/index.js
js/pages/configuration/routes.js
js/pages/configuration/sources/source-manager.js
js/services/SourceAPI.js

As part of #1565 
+ Fixes #1975 
- Moved code related to Configuration Sources from Model.js to sharedState
- Changed Configuration page to extend from Page and not from Component
- Added ability to come back to opened source and see status (unsaved/opened) in sidebar menu
- New source has id of 0 instead of 'new' in url to be consistent with other new entities
- Added alert message when loading of source failed(ex. when trying to load source with unexisted id)
- Removed blinking of form when deleting source and going back to configure page.

Fixed configuration and source manager pages

---

js/Model.js
js/services/CohortDefinition.js

Updates calls to getCohortDefinition endpoint to handle string expression result.
Depends on OHDSI/WebAPI#1262.

[2.7.3] Adjust getCohortDefinition() to handle string expression.

---

js/components/Chart.js
js/components/charts/chart.html
js/components/charts/chart.less
js/components/charts/sunburst.js
js/components/nav-pills.html
js/components/nav-pills.js
js/components/nav-pills.less
js/extensions/bindings/dynamicDatatableBinding.js
js/extensions/bindings/main.js
js/pages/pathways/components/tabs/pathway-results.html
js/pages/pathways/components/tabs/pathway-results.js
js/pages/pathways/components/tabs/pathway-results.less
js/pages/pathways/components/tabs/pathway-tableview.html
js/pages/pathways/components/tabs/pathway-tableview.js
js/pages/pathways/components/tabs/pathway-tableview.less
js/utils/ChartUtils.js
js/utils/CsvUtils.js

References issues: #2117, #1552, #1554. #1451.
This PR's primary focus is #1552 (I gave this a bad branch name), where a tabular view of the sunburst is presented and can be exported one at a time.  I think it would be useful to support a 'export all' button but I did not get to that point.
Other issues I would like to address, but could use some help: 
#1554/#2117: I thought we had the ability to grab a SVG from the browser and save it as a PNG (like we can save a .csv file from tabular data) but I can't find where we did this.  If anyone can provide a function to do this, we can make exporting the sunburst SVG part of this PR.
_**Edit**_: I think I found it in `ChartUtils.downloadAsPng()`.
#1451/#1557: This request is more of a summary statistics view of the sunburst data, and I have …

Implementation of exporting pathway analysis data.

---

js/config.js

if auth providers array is redefined in config-local.js then it is used instead of auth providers array from config.js

---

js/pages/cohort-definitions/cohort-definition-manager.css
js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/cohort-definitions/routes.js
js/services/Sample.js
js/settings.js

Depends on OHDSI/WebAPI#1657.
Thank you Andries Purnal (Andries.Purnal@ucb.com),  Florence Giesen (Florence.Giesen@ucb.com), @MaximMoinat and The Hyve for their implementation, which this PR is based on.
This is the simplified cohort sample functionality which allows a sample to be pulled from a source, and then navigated to the current patient profile UI.

Added simplified cohort sample UI.

---

js/pages/pathways/components/tabs/pathway-design.html

There is some confusion when using 'combination' in the context of pathway analysis:  combinations are sometimes described in drug utilization studies separately from 'switches', so this setting makes it sound like a way to identify 'drug combination use', when the actual purpose is to 'combine dates within a proximity of each other into a single date'.   So, we're changing the wording of this to 'collapse days' and provide a description of what this setting does (it reassigns dates that are in close proximity to each other to reduce pathway variation and reduce noise.)

Update 'Combination Window' description

---

js/components/conceptset/ConceptSetStore.js
js/components/conceptset/conceptset-list.js
js/components/conceptset/const.js
js/pages/concept-sets/components/tabs/conceptset-expression.js
js/pages/concept-sets/conceptset-manager.js

* issue-2410 - fix included concepts tab
* added condition to load included concept sets only when tab is opened
* removed logs
* issue-2410 - moved observer to conceptset-manager.js
* issue-2410 - fixed observer for conceptsets, removed redundant func call
* separate view logic from store
Co-authored-by: wivern <vitaly.koulakov@gmail.com>
(cherry picked from commit 0c7fb56)

issue-2410 - fix included concepts tab (#2413)

---

js/components/analysisExecution/analysis-execution-list.js

PLE/PLP analysis TypeError Cannot read property 'filter' of undefined after closing by ‘close’ button #2447

---

js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js

fixes #2441
@anthonysena 
Concerning expected behavior. Read-only version available for user with "Atlas users" role. If user have only "public" role, then after the fix Atlas will show him this screen:

Configure access modal fails on cohort definition load #2441

---

Dockerfile

Fixes a docker build failure when a gzipped file is already present in `node_modules`.

Fix docker build when a gzipped file already exists

---

docker/30-atlas-env-subst.sh

Otherwise, the "/" is added even if the WEBAPI_URL is empty, making it impossible to avoid running the `envsubst` command, e.g. when trying to mount a custom config-local.js as read-only.

Only add a slash to the WEBAPI_URL if it is set

---

js/components/cohortbuilder/components/VisitOccurrenceTemplate.html

Fixes #2594. 
PlaceOfServiceDistance() is undefined, not null. So strict comparison `PlaceOfServiceDistance() !== null` returned `true`.

 Add Visit Criteria - shows place of service attribute #2594

---

js/components/conceptset/utils.js
js/components/conceptsetInclusionCount/conceptsetInclusionCount.html
js/components/evidence/components/negative-controls.js
js/components/userbar/user-bar.html
js/extensions/bindings/datatableBinding.js
js/pages/cohort-definitions/components/reporting/cost-utilization/report-manager.html
js/pages/concept-sets/components/tabs/conceptset-compare.js
js/pages/concept-sets/conceptset-manager.html
js/pages/configuration/configuration.js
js/pages/configuration/roles/role-details.html
js/pages/configuration/roles/roles.html
js/pages/vocabulary/components/search.js
js/styles/atlas.css

 Loader icon does not show (font-awesome icon "fa-circle-notch") #2702

---

Dockerfile
docker/nginx-default.conf

Closes #2641
When accessing the Atlas UI on a URL *not* ending in a trailing slash, NGINX would always automatically redirect you to `host:8080/atlas/`.
This change modifies the default NGINX configuration to use the host header for redirection.

Fixed invalid redirect for /atlas without trailing slash

---

js/components/heading.less
js/pages/data-sources/classes/Treemap.js
js/pages/data-sources/components/reports/treemap.html
js/pages/data-sources/components/reports/treemapDrilldown.html
js/pages/data-sources/components/reports/treemapDrilldown.js
js/pages/data-sources/data-sources.html
js/pages/data-sources/data-sources.js
js/pages/data-sources/data-sources.less

 Add notification of generated visuals within “Data Sources” upon drilldown #2725 

---

js/extensions/bindings/i18nBinding.js

Fixes #2745.
Lodash templates cache moved to i18n/templates. Templates duplication is fixed, now caching only unique templates by message key - maximum number of cached templates is a number of parametrized i18n messages (which is now around several tens).

 i18n problem with lodash templates #2745

---

js/pages/estimation/cca-manager.js
js/pages/prediction/prediction-manager.js

Fixes #2760
`createdBy` and `modifiedBy` as objects stored outside the specification of PLP/PLE. Inside the spec server expect just a string.

 Cannot export PLP/PLE after second save #2760

---

index.html
js/Application.js
js/config/app.js
js/utils/BrowserDetection.js

For #2845: adds a config setting named "disableBrowserCheck", which will default to false (meaning, run the browser check and toggle the warning if not a supported browser). Setting this to true will disable the browser check and warning.
To do this, I removed the existing BrowserDetection JS script and instead have a knockout data bind that runs toggleBrowserWarning() to handle this decision.

Adds ability to disable browser check via config

---

js/components/dataSourceSelect.js
js/pages/vocabulary/components/search.html
js/pages/vocabulary/components/search.js

Correct vocabulary for person counts is used

---

.gitignore
js/components/security/access/configure-access-modal.html
js/components/security/access/configure-access-modal.js
js/config/app.js
js/pages/characterizations/components/characterizations/characterization-view-edit.html
js/pages/characterizations/components/characterizations/characterization-view-edit.js
js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html
js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/concept-sets/conceptset-manager.html
js/pages/concept-sets/conceptset-manager.js
js/pages/estimation/cca-manager.html
js/pages/estimation/cca-manager.js
js/pages/incidence-rates/ir-manager.html
js/pages/incidence-rates/ir-manager.js
js/pages/pathways/components/manager.html
js/pages/pathways/components/manager.js
js/pages/prediction/prediction-manager.html
js/pages/prediction/prediction-manager.js
js/pages/reusables/components/manager.html
js/pages/reusables/components/manager.js
js/services/Permission.js

Adding the ability to see read permissions alongside of write permissions Added flag enablePermissionManagement to control UI element to assign permissions.

Add read permissions (#2849)

---

js/components/atlas.cohort-editor.html
js/components/circe/components/ConceptSetBrowser.js
js/components/from-reusables-modal/from-reusables-modal.html
js/extensions/bindings/datatableBinding.js
js/services/AuthAPI.js

Aims to fix #2887 by extending the concept set browser to only load the repository concept set list when the modal is activated.

Prevent multiple calls to concept set list when loading cohort editor

---

js/services/AuthAPI.js

Bypass refreshToken() when authentication is not enabled.

---

js/pages/configuration/configuration.html
js/pages/configuration/configuration.js
js/services/AuthAPI.js

This PR starts to address the issues raised in #2908.
To test, there was a button added on configuration and will attempt to run all isPermittedXXX() methods on authAPI, and report the elapsed time.
The timings for old vs new are:
```
-- Origional code
Script execution time: 5.400000095367432 milliseconds
configuration.js:278 Script execution time: 4.100000023841858 milliseconds
configuration.js:278 Script execution time: 3.600000023841858 milliseconds
configuration.js:278 Script execution time: 4 milliseconds
configuration.js:278 Script execution time: 3.799999952316284 milliseconds
configuration.js:278 Script execution time: 3.9000000953674316 milliseconds
configuration.js:278 Script execution time: 3.399999976158142 milliseconds
configuration.js:278 Script execution time: …
```

Optimize Permission handling on ui

---

js/components/authorship.html

This commit is about the issue: https://github.com/OHDSI/WebAPI/issues/2381
And the commit involved in WebAPI: https://github.com/OHDSI/WebAPI/pull/2382

fix The Korean sentence order in Authorship description

---

js/components/faceted-datatable.js
js/components/reports/classes/Treemap.js
js/components/reports/reportDrilldown.js

This PR fixes 2 different UI bugs that I have encountered in using the Atlas Data Sources reports.
- If the request to get the data for a report for some reason returns an empty array, the tabular view showed a perpetual spinner. I have update the TreeMap.js code to set the tableData parameter to an empty array in this case so that the code that turns off the spinner has an opportunity to execute.
- The frequency distribution report failed to display because there was a bug in how the chart's x-axis label is generated. A recent PR changed the `parseFrequencyDistribution` function signature so that it now passes in a string, rather than a function, for the `report` parameter. (https://github.com/OHDSI/Atlas/pull/2806/files#diff-ea4bfc7a6c32110ea437c23665e2c52aea4d576102f87d5f808e40eead04517 …

Data Sources reports bug fixes

---

Dockerfile

Atlas docker image is using a deprecated nginx that have been now in "End of life"
This commit will be update the nginx to the 1.27.2

Update nginx to 1.27.2

---

js/pages/cohort-definitions/cohort-definition-manager.css
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/incidence-rates/components/iranalysis/components/results.js
js/pages/incidence-rates/components/iranalysis/components/results.less

Modifies the cohort generation & IR generation displays based on #2878. From the issue description:
> 1. Hover Style: if the row that you were hovering was highlighted, you could see that a generate button is associated with a source more clearly.
> 2. Re-arrange columns: move Generate button to first column so the button is right next to the source
> 3. Table Style: add borders to table to see the alignment better.
The generation buttons are moved to the left (along with other buttons since those are all in the same HTML template). In this PR, I added the hover style (see below) and opted to add the borders on hover. We could always display the border but thought this might work as well and keep the table looking clean.
Same changes were done for the IR display in this PR:

Clearer table boundaries on generate UI

---

js/pages/profiles/profile-manager.js

Removes the HTML and instead shows the concept set name with the "(Concept Set)" suffix to distinguish it from the single concepts that appear in the event highlighting.

Change concept set display in patient profile - fixes #2815

---

js/components/multi-select.html
js/components/multi-select.js
js/pages/characterizations/components/feature-analyses/fa-view-edit/fa-design.html
js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html

Modifies the custom feature editor to allow for browsing concept sets when in read-only mode per #2532. These changes also enable the copy SQL to clipboard per #2812.

Allow read-only custom feature browsing

---

.editorconfig
js/pages/configuration/configuration.js
js/services/CacheAPI.js
js/services/SourceAPI.js

closes https://github.com/OHDSI/Atlas/issues/2847
Companion PR is https://github.com/OHDSI/WebAPI/pull/2406
I added an .editorconfig file so that this project can have its own style conventions. I noticed that there were mixed spaces/tabs and tab sizes within individual files. I recommend turning whitespace diffs off when reviewing this PR.
There was an existing Clear Server Cache button. I have it pointing now to the new webapi/cdmResults/clearCache endpoint. I fixed the code so that if the clearCache operation returns an error response we alert the user.

Have the Clear Server Cache button clear the cdm_cache and achilles_cache tables

---

js/services/CacheAPI.js

With the introduction of caching in OHDSI/WebAPI#2393, we have a middle-tier cache that contains auth info and entity list caches.  This PR reverts a change that had the clear server cache button refresh the CDM caches, and instead will clear the webAPI cache.
You can still clear individual CDM caches using the individual 'refresh cache' buttons in the configuration ui.

Switch clear-server cache button to clear webapi cache.

---

js/components/analysisExecution/analysis-execution-list.html
js/components/analysisExecution/analysis-execution-list.js
js/components/analysisExecution/shiny-const.js
js/pages/cohort-definitions/cohort-definition-manager.html
js/pages/cohort-definitions/cohort-definition-manager.js
js/pages/cohort-definitions/const.js
js/pages/incidence-rates/components/iranalysis/components/results.html
js/pages/incidence-rates/components/iranalysis/components/results.js
js/pages/incidence-rates/const.js
js/services/file.js

Addressing [#2349](https://github.com/OHDSI/WebAPI/issues/2349)

Cohort and analyses execution / generation listings extensions with a button to publish/download Shiny applications

---

js/components/multi-select.html

See also https://github.com/OHDSI/Atlas/pull/2975/files#r2040084688
Fixes error below:
```
knockout-latest.js:16 Uncaught ReferenceError: Unable to process binding "if: function(){return multiple == true }"
Message: Unable to process binding "attr: function(){return disabled }"
Message: disabled is not defined
```

Fix: adjust attribute name "disable" to match what is defined in multi-select.js

---

js/config.js

Fix the AMD factory to inject Lodash as _, matching the symbol the module uses
- Prevents _.mergeWith/_.isArray from falling back to a global lodash object and throwing when it’s
unavailable
- No functional behavior change beyond ensuring the config merge logic consistently works in environments
without a global _

fix: use _ alias for lodash in config module
